Feat: mainTabView, homeView, recordView, storeView
depromeet/mongsil-iOS pull request #20
Opened 2022-04-15 08:08 UTC by MoSonLee

### Task
   - Add TabView and Hierarchy
 
 ### Description 및 사용안내

   - MaintabView를 생성해 homeView, storeView, recordView로 이동하는 button을 넣어주어 초기 화면을 구성했습니다</br>
      - appVIew에서 진입 view가 homeView -> mainTabView로 수정되었습니다.</br>
   - tabbar line을 생성해주었습니다.</br>
   - 모듈화 되어 있는 MSNavigationBar, backbutton을 사용해 코드를 core에 초기화면으로 돌아가게 구현했습니다.</br>
   - 아직 wireframe단계라 layout은 임의로 해놓고 나중에 이미지, 폰트 등을 추가할 수 있게 구현했습니다.</br>
      - 추후에 디자인이 확정되면 layout과 이미지는 교체예정입니다.</br>

2022-04-15 08:33 UTC, GREENOVER commented
@MoSonLee 
우선 코드리뷰 전 뷰 버튼의 위치가 달라지는 이슈가 있어 공유드립니다!
기록하기 버튼을 보시면 초기 앱이 실행되었을때 위치와 보관함 및 다른 버튼을 클릭한 후 부터 쭉 위치가 다른걸 볼 수 있습니다🙋🏻
![Simulator-Screen-Recording-iPhone-11-2022-04-15-at-17 30 57](https://user-images.githubusercontent.com/72292617/163547074-a6e4c5d2-207d-4088-b558-e02410fbc176.gif)

2022-04-15 11:04 UTC, GREENOVER requested changes
전체적으로 우선 수정이 필요한 부분에 대해 코멘트 남겼습니다! 이와 슬랙에서 말씀드린 인덴트 및 개행에 대해 저희가 정한 컨벤션을 따라주시면 좋을것 같아요🙌🏼 버튼이 움직이는 그 이슈는 아마 코멘트를 토대로 수정하다보면 실마리가 있을것 같네요!
수정 후 리뷰 재요청을 해주시면 됩니다🙋‍♂️

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft";
저희는 가로모드에 대해 지원하지 않으니 해당 설정은 제거하는게 좋을것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +//  TabView.swift
MainTabView인데 주석에서 나타난 해당 파일명은 TabView로 통일이 되야할것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +//  recordCore.swift
MainTabCore가 되야할것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +struct TabState: Equatable {
보통 MainTabState로 해당 코어의 네이밍을 전부 붙여줘야 혼동이 없습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public  var homeState: HomeState = .init()
띄워쓰기가 한칸 더 되있는것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public var storeState: StoreState = .init()
보통 State 타입을 변수로 만들때 home, record, store라고만 명시하고 뒤에 State를 붙여주지 않게 사용하는데 이와 같은 네이밍은 어떨까요?🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        isBackToHomePushed: Bool = false
isRecordButtonTapped은 이니셜해주지 않아도 괜찮은가요?🤔

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +enum TabAction: Equatable {
여기서 MainTabAction이 되야할것 같습니다

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +enum TabAction: Equatable {
Equatable 프로토콜은 왜 따라준건지 궁금합니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case backButtonTapped
이 액션은 어디서 사용되나요?
실제적 쓰임이 없을것 같아서요!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
액션 케이스 네이밍을 지정할때도 home, record, store와 같이 표현하는게 더 적합할것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +struct TabEnvironment {
MainTabEnvirionment 네이밍이 더 적합할것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
이니셜라이저를 활용해주세요🙏🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +
개행은 필요없을것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +                        ),
리듀서 풀백한 부분들 코드 개행 및 들여쓰기 컨벤션을 맞춰보면 어떨까요?
이는 Setting 부분을 참고해보면 좋을것 같습니다!
현재는 가독성이 너무 떨어집니다😭

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
얘만 타입 캐스팅이 되어있고 위에는 되있지 않은 특별한 이유가 있을까요?🙋🏻
한쪽으로 통일되면 좋을것 같아요!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
>와 { 사이 한칸 공백만 있으면 되지 않을까 싶습니다.

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +            if isTapped{
보통 Swift 문법에서는 isTapped { 로 한칸 띄워 가독성을 높여 표시해줍니다.

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +            return .none
실제적으로 필요하지 않는 즉 앞으로도 쓰일일이 없어 보이는 액션인것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
MainTabView단에서는 WithSharedState로 State를 정의했기에 Core에서도 이를 맞춰줘서 타입을 지정해줘야할것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        case let .setBackToHome(ispushed):
pushed의 네이밍이 더 어울릴것 같아요!
pushed 자체가 판별의 의미를 지녔다고 생각합니다.

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        case .recordAction:
개행이 필요해 보입니다.

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +    let store: Store<WithSharedState<TabState>, TabAction>
이니셜라이저가 있어서 private해도 괜찮을것 같습니다.

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +
불필요한 개행인것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                                )
별도로 변수로 만들어 body 밖에서 이니셜해주고 그걸 받아와 사용하는게 더 나을것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +    var body: some View {
body안에 각 뷰들이 너무 많이 들어있습니다.
해당 View 파일 안에서 얘네들을 private View로 쪼개서 구성하고 불러와보는게 좋을것 같습니다!
SettingView쪽을 한번 보시면 도움이 될것 같아요!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +//  recordCore.swift
RecordCore가 되야할것 같습니다🙋🏻

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +//  recordView.swift
RecordView가 되야할것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
파일명에 네이밍 오탈자가 있습니다!
추가로 저희 코드에서 viewstore와 같이 Store 네이밍의 개념이 많이 사용되는데 Storage라는 네이밍은 어떨까요?

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Application/AppCore.swift
> +    var mainTab: TabState = .init()
2칸 인덴트 부탁드립니다..!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +    public var isBackToHomePushed: Bool = false
이 변수는 어떻게 쓰이는건가요?

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +enum HomeAction: Equatable {
Equatable을 채택해주신 이유가 있을까요??

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +import SwiftUI
코어에서 SwiftUI를 임포트할 필요가 있을까요?

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public var isBackToHomePushed: Bool = false
해당 프로퍼티가 어떻게 사용되나요?

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +        WithViewStore(store.scope(state: \.local.isRecordButtonTapped)) {isRecordViewPushedViewStore in
해당 스코프에 대해 불리는 뷰에서만 호출되는게 맞을것 같아요! 실제로 주 isButtonTapped의 값이 전달될 뷰만 감싸주면 됩니다..!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +
불필요한 개행인것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
요 라벨에 위에 있는 해당 기록하기 버튼이 들어있는게 맞을것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    storeReducer.pullback(state: \.storeState,
해당 보관함 리듀서를 풀백 받아와서 아무것도 안해주고 있는데 추후 어떤걸 해주게 되는걸까요?

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    homeReducer.pullback(state: \.homeState,
홈리듀서에 대해 풀백 받아오고 사실 아무것도 해주지 않는데 넣어주신 이유가 궁금합니다🙋‍♂️

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
사실상 선언은 하고 사용되고 있진 않는것 같아요!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +                NavigationView{
네비게이션뷰로 해줄 필요가 없을것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        WithViewStore(store) { viewStore in
현재 버튼 액션에 바로 스토르를 ViewStore에 담아 해주고 있기에 해당 WithViewStore로 감싸줄 이유는 없을것 같아요! 사실상 viewStore 인자를 사용해주는곳이 없습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreCore.swift
> +//  collectionCore.swift
파일 네이밍이 다릅니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +//  collectionView.swift
파일 네이밍이 다릅니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +            NavigationView {
네비게이션뷰가 들어갈 이유가 없을것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +        WithViewStore(store) { viewStore in
사실상 viewStore인자가 사용되는곳이 없기에 현재는 제거해도 될것 같습니다!

2022-04-15 11:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +                    .navigationBarTitle("보관함", displayMode: .inline)
만들어진 MSNavigationBar를 사용해주세요!

2022-04-15 13:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +//  TabView.swift
수정했습니다

2022-04-15 13:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +//  recordCore.swift
수정했습니다!

2022-04-15 13:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +struct TabState: Equatable {
수정했습니다!

2022-04-15 13:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public  var homeState: HomeState = .init()
수정했습니다!

2022-04-15 13:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public var storeState: StoreState = .init()
수정했습니다!

2022-04-15 13:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        isBackToHomePushed: Bool = false
수정했습니다!

2022-04-15 13:57 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +enum TabAction: Equatable {
수정했습니다!

2022-04-15 13:57 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +enum TabAction: Equatable {
수정했습니다!

2022-04-15 13:58 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case backButtonTapped
수정했습니다!

2022-04-15 13:59 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
수정했습니다!

2022-04-15 14:00 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +struct TabEnvironment {
수정했습니다!

2022-04-15 14:09 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
<img width="482" alt="image" src="https://user-images.githubusercontent.com/77050826/163580855-ead96330-ebff-462e-a96d-f2ea9f725ed5.png">
이렇게 수정했습니다  근데 이렇게 사용하면 세줄이 더 길어지는데 이렇게 사용하는 것이 맞나요?!

2022-04-15 14:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +
수정했습니다!

2022-04-15 14:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
수정했습니다!

2022-04-15 14:12 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
아뇨! 이니셜라이저 인자로 인스턴스를 받아와야함니다..!

2022-04-15 14:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +                        ),
수정했습니다!

2022-04-15 14:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
수정했습니다!

2022-04-15 14:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +            if isTapped{
수정했습니다!

2022-04-15 14:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +            return .none
수정했습니다!

2022-04-15 14:46 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    as Reducer<TabState, TabAction, TabEnvironment>, Reducer<TabState, TabAction, TabEnvironment>   { state, action, env in
전부 WithSharedState로 수정했습니다!
왠지 local이 안 써졌었는데 이유를 찾았네요!! 
감사합니다 ㅎㅎ

2022-04-15 14:47 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        case let .setBackToHome(ispushed):
수정했습니다!

2022-04-15 14:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +        case .recordAction:
수정했습니다!

2022-04-15 14:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +    let store: Store<WithSharedState<TabState>, TabAction>
수정했습니다!

2022-04-15 14:49 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +
수정했습니다!

2022-04-15 14:59 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +//  recordCore.swift
수정했씁니다!

2022-04-15 15:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +//  recordView.swift
수정했습니다!

2022-04-15 15:02 UTC, MoSonLee commented on Mongsil/Mongsil/Application/AppCore.swift
> +    var mainTab: TabState = .init()
수정했습니다!

2022-04-15 15:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +enum HomeAction: Equatable {
수정했습니다!

2022-04-15 15:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +import SwiftUI
수정했습니다!

2022-04-15 15:07 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    public var isBackToHomePushed: Bool = false
예전에 시도할때 해둔걸 못 지운것 같습니다! 
수정했습니다!

2022-04-15 15:09 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +
수정했습니다!

2022-04-15 15:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    storeReducer.pullback(state: \.storeState,
앗 풀백을 할 떄 일단 해두었었는데 필요할때 다시 추가하면 되겠네요 
수정했습니다!

2022-04-15 15:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    homeReducer.pullback(state: \.homeState,
처음 풀백을할때 하위 계층 모두를 일단 풀백해놔야한다고 생각했습니다!
수정했습니다!!

2022-04-15 15:15 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/77050826/163588131-19fc97fa-68d5-4286-8519-4bece2950adf.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/77050826/163588161-e39d742a-9ab6-45fe-8c56-6d66fb9dec2c.png">

여기서 사용해주고 있는데 혹시 잘못된 것일까요?!

2022-04-15 15:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +                NavigationView{
![image](https://user-images.githubusercontent.com/77050826/163588326-ce0185ea-4444-472c-8578-d671026b2764.png)
navigationView로 진행하지 않으면 화면이 이런식으로 뜹니다!

2022-04-15 15:17 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        WithViewStore(store) { viewStore in
그렇네요! 수정했습니다!

2022-04-15 15:17 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +//  collectionView.swift
수정했습니다!

2022-04-15 15:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +            NavigationView {
리뷰 받기전에 찾았냈었는데 역시나 이 친구였네요 버튼을 올라가게 한게...😂
수정했습니다!

2022-04-15 15:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +        WithViewStore(store) { viewStore in
넵 수정해주었습니다!
같은 실수가 계속 나오는데 아마
처음 쓰는 아키텍쳐 문법을 찬우님 코드를 보면서 구현해서 
기능은 알아도 빠져도 되는지를 자꾸 체크하지 못했던 것 같습니다!
이번 코드 리뷰 이후론 조금씩 더 흡수를 해서 더 좋은 코드를 작성해보겠습니다!

2022-04-15 15:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Store/StoreCore.swift
> +//  collectionCore.swift
수정해주었습니다!

2022-04-15 15:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
<img width="471" alt="image" src="https://user-images.githubusercontent.com/77050826/163589752-ef61b3b0-e857-4ff6-9288-e806e67ec95f.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/77050826/163589794-a115b074-ca7e-4590-88a7-857e316c38e9.png">

appcore에서 인스턴스를 받아와서 치러해주었습니다!

2022-04-15 15:30 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft";
이 코드를 찾을수가 없습니다..ㅋㅋㅋㅋ 뭔가 설정에서 건드렸나 보이지가 않네요 ㅜㅜ
<img width="279" alt="image" src="https://user-images.githubusercontent.com/77050826/163589890-521872ae-5408-4db6-be6b-f55af6a8f08e.png">

2022-04-15 15:31 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
맨 위 질문과 같습니다!
이쪽 파일은 어떤 경로로 들어갈 수 있나요?!

2022-04-15 15:32 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +    public var isBackToHomePushed: Bool = false
수정했습니다!

2022-04-15 15:38 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
아 그렇네요 수정했습니다!

2022-04-15 15:50 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft";
타겟에서 확인할 수 있습니다!

2022-04-15 15:52 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
이건 단순히 옆 파일 트리에서 네이밍을 보시면 됩니다

2022-04-15 15:52 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
다르게 해석된것 같아요! 이니셜라이저에 대해 한번 학습해보시면 좋을것 같습니다!

2022-04-15 15:54 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +                NavigationView{
이건 뷰를 스페이스들 두어 구성하셔서 해결해야될 문제입니다

2022-04-15 16:15 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +                NavigationView{
<img width="200" alt="image" src="https://user-images.githubusercontent.com/77050826/163594687-0730e760-3327-4aba-80a4-e860603238d2.png">
Navigationview는 지워준 후
 spacer을 주어 해결했습니다

2022-04-15 16:18 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
스토어와 홈은 사용이 안되는거 아닐까요? 사용이 안되는걸 액션으로 만들고 뷰를 이닛해줄 필요는 없어보입니다!

2022-04-15 16:25 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
수정시 navigationlink안에 버튼이 있어서 그런지 버튼이 눌리질 않습니다!
label안에 넣어주는 이유가 무엇인가요?! 다시 생각해보니 궁금해서요!

2022-04-15 16:32 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
<img width="322" alt="image" src="https://user-images.githubusercontent.com/77050826/163596276-047d67e5-90fa-4a71-a621-1ed685fabe2a.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/77050826/163596348-840c0f60-04f0-4668-84ff-127a715b214b.png">

하나씩 주석처리를 해보고 코드를 실행해보는데 문제가 생기고 있습니다!

2022-04-15 16:35 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +        WithViewStore(store.scope(state: \.local.isRecordButtonTapped)) {isRecordViewPushedViewStore in
헉 무조건 맨위에 선언해서 최상위로 감싸줘야하는줄 알았습니다! 
감사합니다 앞으론 더 생각하며 넣어주겠습니다!

2022-04-15 23:45 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
해당 액션이 없는데 뷰 생성 시 이니셜라이저로 액션을 넘겨줘서 오류가 생기는것입니다! 이니셜라이저에 대해 한번 기본을 학습해보시면 좋을것 같아요!

2022-04-15 23:50 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
해당 네비게이션 링크에서 레이블은 그냥 이 네비게이션 링크를 나타내는 뷰가 될것 같아요. 텍스트라던지 이미지라던지 그런? 버튼이 눌리지 않는것은 다른 문제 같은데 어떠한 구현이 빠졌다던가 하는게 있는지 한번 다른쪽 네비게이션링크가 구현된 부분의 코드와 비교해보면 어떨까요?

2022-04-16 01:26 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
아마 쉽게 생각해보시면 저 버튼이 안눌리는게 아니라 저 버튼보다 밑에 위치시켜 탭해보시면 눌려지는걸 볼 수 있습니다.
그럼으로 레이아웃 문제이겠죠🤔

2022-04-17 09:36 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +                            label: {
아 찬우님 말슴대로 버튼 위치를 바꿔보니 액션이 실행되는 걸 보고 layout 문제인걸 알고
수정했습니다 감사합니😀

2022-04-17 09:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
<img width="222" alt="image" src="https://user-images.githubusercontent.com/77050826/163709041-aaac993d-e11e-4d37-9719-c6ef94d75761.png">
이 쪽 선언해주는 부분을 지워줬습니다!

2022-04-17 11:51 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
StoreView 이름 자체를 StorageVIew로 바꾸는게 좋겠다는 말씀이신가요?!

2022-04-17 11:55 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
네 제가 말씀드린 의도는 그거였습니다!

2022-04-17 11:56 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
음 올바른 해결방법은 아닌것 같습니다!
다른쪽에서는 어떻게 했나 한번 보시는것도 방법일것 같아요.

2022-04-17 12:00 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft";
확인하고 지워줬습니다!

2022-04-17 12:03 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		773AE2AE28072419006861FC /* StoreViw.swift in Sources */ = {isa = PBXBuildFile; fileRef = 773AE2AD28072419006861FC /* StoreViw.swift */; };
수정했습니다!

2022-04-17 12:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
아 다른 코드들에선 저거 세개를 그냥 선언해주었는데 그럼
저도 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/77050826/163713528-99cc7d00-d407-4834-910c-83fe2e4dd88c.png">
요런식으로 선언만 해주면 되는걸까요? 
아까 코드에선 sotre관련된 action이 선언이 안되었던거 같습니다!

2022-04-17 12:59 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
이 액션을 왜 선언해줘야하는걸까요?
뷰를 이닛해주기 위해서 지금 이 작업을 해주시는건데 최초 말씀드렸던 의도는 뷰 이닛을 지금과 같은 방식으로 해줄 필요가 없습니다.

2022-04-17 13:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    case storeAction(StoreAction)
아 무슨 말인지 이해했습니다! 위에 있는 init과도 연관 이 있겠네요!
Init 관련해서 다시 한번 생각해보겠습니다!

2022-04-17 14:47 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +                    .navigationBarTitle("보관함", displayMode: .inline)
여기는 backbutton이 없는데도 MSNavigationBar을 사용할라면 backbutton을 선택할 수 있는걸 MSNavigationBar에 추가해야할까요?

2022-04-17 14:50 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +    var body: some View {
수정했습니다!

2022-04-17 15:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +    var storeEnvironment: StoreEnvironment = .init()
<img width="320" alt="image" src="https://user-images.githubusercontent.com/77050826/163720942-220411eb-8cd8-4e54-96f9-23ea22c86f69.png">

reucer안에서 init해서 수정해주었습니다

2022-04-17 23:10 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Store/StoreViw.swift
> +                    .navigationBarTitle("보관함", displayMode: .inline)
백버튼에 대해 지금 현재는 무조건 들어가게끔 네비게이션바가 구현되있을건데 이걸 호출 시 선택에 따라 나타날수 있게 인자를 추가로 주어 커스텀하게 수정해보면 어떨까요?

2022-04-18 13:56 UTC, GREENOVER commented
@MoSonLee 
컨플릭이 나는걸 처리해야하는데 이건 내일 어떻게 진행하면 되는지 같이 알려드리겠습니다!

2022-04-19 12:19 UTC, GREENOVER approved these changes
같이 페어프로그래밍 진행하며 수정 및 확인하였습니다!
고생 많으셨습니다🙌

2022-04-19 12:21 UTC, merged