feat: Add apple and kakao login service
depromeet/mongsil-iOS pull request #21
Opened 2022-04-15 12:47 UTC by Aki-hwang

### Task

1. Kakao and Apple login service 실행 확인
- Services -> AppleLoginService, KakaoLoginService

2022-04-15 14:29 UTC, GREENOVER commented
@Aki-hwang 
코드 리뷰에 앞서 해당 브랜치 빌드 되시나요?

2022-04-15 14:49 UTC, GREENOVER requested changes
우선적으로 전체적으로 뷰를 구성해주실 필요가 없습니다.
서비스에서는 딱 해당 애플/카카오 로그인을 위한 비지니스 로직만 메서드화 시켜 만들어주시는것이 이번 테스크였습니다.
이건 컴포저블 아키텍쳐와는 무관하고 정말 딱 컴바인까지만 사용해 메서드를 만든다는 생각으로 접근하시면 될것 같아요.
코멘트를 남기긴 했는데 전체적으로 구성이 조금 어긋난 부분이 많아서 유의미하게 작용할진 모르겠지만 한번 코멘트를 보고 일차적으로 수정해보시고 또 얘기를 나눠보시죠!

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
해당 필드가 바뀐데는 이유가 있을까요?🙋🏻

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.Mongsil.aki;
실 디바이스 테스트를 위해 바꾸신거라면 PR시에는 기존과 같이 원복하는게 맞을것 같습니다🙋🏻

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +struct AppleLoginView: View {
서비스에는 딱 서비스만 들어와야합니다.
이러한 뷰 및 코어의 로직은 관심사를 분리해야될것 같아요.

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +  @Environment(\.colorScheme) var colorScheme
이건 이미 메인에 반영되어 있는 코드이니 제거되어도 될것 같습니다!

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +          )
저희 디자인에서는 다크 테마로만 이뤄져있고 아직 라이트 모드에 대한 언급이 없으니 굳이 필요하지 않은 디자인이자 기능일것 같습니다!

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +}
사실상 프리뷰는 의미가 없다고 보입니다.
없는게 컴파일 성능에 더 도움이 될것 같아요!

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +                print("lastName \(lastName ?? "")")
사실상 이 PR이 메인에 합쳐진다고 생각해보면 이 코드들은 테스트용이니 전부 제거하고 PR을 올리는게 맞을것 같습니다ㅣ!

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +              print(error)
딱 여기까지가 애플 로그인 서비스에서의 비지니스 로직입니다.
이 부분만 AppTrackingService를 보시면서 그러한 구성으로 메서드로 추출하여 살려보시는게 나을것 같아요.
핵심은 메서드화 시킨다고 생각하시면되요.
인자 받고 리턴값을 내뱉는 메서드로요!
요건 컴포저블 아키텍쳐도 아닌 딱 컴바인이기에 해당 부분을 숙지하시고 찾아보시면 좋을것 같아요.

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
KakaoSDK가 import가 되나요?
혹시 빌드도 되시나요?

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +struct ContentView: View {
여기도 위 애플 로그인 서비스와 마찬가지로 딱 비지니스 로직만 있어야합니다.
뷰는 여기의 관심사가 아닙니다.

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +  @State var appleUserMail : String = ""
컴포저블과 연관된다면 해당 프로퍼티들은 여기 있을 이유가 없습니다.
Core에서 State안에서 상태관리를 해줘야합니다.

2022-04-15 14:49 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +  }
이러한 카카오 로그인 연동을 위한 로직만을 서비스에 담는다고 생각해보시면 좋을것 같아요.
위에 뷰는 관심사가 아님으로 구성해줄 필요가 없습니다!

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +  }
카카오 서비스에 애플 로그인이 들어올 이유가 없을것 같아요

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDKAuth
구현해주신걸 보면 KakaoSDKCommon과 KakaoSDKAuth 라이브러리는 전혀 쓰이지 않고 있습니다.
다른 라이브러리 추가가 필요하지 않을까요?

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
클로저 인자로 User를 대문자로 시작해 네이밍을 해주신 이유가 있을까요?
[Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming)에 어긋납니다.

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
error를 클로저로 받아와 전혀 사용해주지 않고 있는데 필요한 인자일까요?

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      if let nickName = User?.kakaoAccount?.profile?.nickname{
nickname은 보통 한단어로 취급되기에 카멜케이스를 따라줄 필요가 없을것 같습니다!

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      if let nickName = User?.kakaoAccount?.profile?.nickname{
통상적으로 클로저 시작부 즉 { 앞에 한칸 띄우는 컨벤션을 사용합니다.

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      }
위와 여기도 그렇고 if let으로 바인딩해주신 이유가 어떤건지 궁금합니다🙋🏻

2022-04-16 02:17 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
아마도 이게 철진님 개인 계정의 TeamID로 부여됐기에 승후님과 저는 이런 방식에서는 철진님의 account를 추가할 수 없어 실제 디바이스에서는 테스트가 불가능할거에요🥲

2022-04-16 02:29 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +        if (UserApi.isKakaoTalkLoginAvailable()) {
이 메서드에서 오류를 나타냅니다.
`-canOpenURL: failed for URL: "kakaokompassauth://authorize" - error: "This app is not allowed to query for scheme kakaokompassauth"`
실제로 디바이스에서 카카오톡 연동 로그인 버튼을 클릭하면 위와 같이 isKakaoTalkLoginAvailable 메서드 내부 호출부인 canOpenURL에서 kakaokompassauth 스킴을 허락하지 않았다 어쩌구~ 하고 에러를 뱉는걸 볼 수 있습니다.
혹시 카카오톡 연동 로그인 테스트를 해보신걸까요?
했다면 어떻게 진행되었는지 공유 부탁드립니다.
제 추측에는 info.plist 파일에서 LSApplicationQueriesSchemes해당 스킴 적용된 코드가 없어 발생하는것 같다고 느껴져서요.

2022-04-16 04:58 UTC, Aki-hwang commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.Mongsil.aki;
넵 PR 시에는 원복하겠습니다!!

2022-04-16 04:59 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +          )
넵

2022-04-16 05:00 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +}
넵

2022-04-16 05:11 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
넵 따로 만든 파일에선 빌드 및 실행되 되는데.. 원인을 찾아볼꼐요

2022-04-16 05:18 UTC, Aki-hwang commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
카카오 developer 부분에 권한 관리가 있긴한데 이걸로 추가하면 가능하지 않을까요?

2022-04-16 05:19 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +  @Environment(\.colorScheme) var colorScheme
제거했습니다

2022-04-16 05:19 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +                print("lastName \(lastName ?? "")")
제거했습니다

2022-04-16 05:22 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDKAuth
UserApi << KakaoSDKUser에 포함된 카카오 Open API의 사용자관리 API 호출을 담당하는 클래스입니다.

2022-04-16 05:26 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +        if (UserApi.isKakaoTalkLoginAvailable()) {
넵 어제 재설치 하는 과정에서 LSApplicationQueriesSchemes 부분이 삭제되어 있음을 확인 후 추가 했습니다.

감사합니다.

2022-04-16 05:27 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +  }
넵

2022-04-16 05:28 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
UserApi << 카카오에서 제공하는 사용자관리 API를 사용했습니다.

2022-04-16 05:29 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      if let nickName = User?.kakaoAccount?.profile?.nickname{
네

2022-04-16 05:39 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      }
func me의 User값이 옵셔널이라 if let으로 선언했습니다

2022-04-16 06:21 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
요건 애플 로그인과 관련된거 아닌가요?🤔
혹시 어떻게하는건지 방법을 알고 계시면 공유 부탁드립니다!

2022-04-16 06:22 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
음.. 제가 알기론 KakaoSDK는 라이브러리고 그 하위로 KakaoSDKAuth, KakaoSDKUser와 같은 애들을 불러 사용해야되는걸로 알고 있는데 잘못 이해한걸까요?🤔

2022-04-16 06:23 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDKAuth
네네 그렇기에 KakaoSDKUser만 임포트함녀 되지 않을까요?

2022-04-16 06:24 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
여기서 말씀드린 유저는 클로저 인자에 있는 User입니다..!

2022-04-16 06:25 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      }
제가 여쭤봤던건 guard let도 있었을텐데 if let으로 옵셔널 바인딩을 택해준 이유가 궁금했습니다🙋🏻

2022-04-16 07:31 UTC, Aki-hwang commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
번들아이디 생성시 signinapple 항목을 추가 하시면 됩니다. 

혹시 🥲 이런 이모지는 어떻게 입력하는지 알 수 있을까요?

2022-04-16 07:35 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
알고 계신게 맞습니다. 하지만 우리가 사용하는 서비스에서는 KakaoSDK 중  KakaoSDKAuth, KakaoSDKUser, KakaoSDKCommon 요 3개만 필요해서  그것만 가져왔습니다. 각각의 사용처는 아래와 같습니다.

KakaoSDKAuth >> SceneDelegate에서 사용
KakaoSDKCommon >> AppDelegate에서 사용
KakaoSDKUser >> KakaoLoginService에서 사용

2022-04-16 07:41 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      }
추가적인 조건이 없는 경우 주로 if let으로 사용하고 있습니다. (리턴을 사용할 필요도 없고, 보기 편해서요)

혹시 코멘트 해주실 내용이 있으신가요?

2022-04-16 07:42 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      if let nickName = User?.kakaoAccount?.profile?.nickname{
넵 수정완료 했습니다

2022-04-16 07:45 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
넵 사용하도록 수정했습니다. 

추가적으로 me 함수의 completion에 보면 error 값을 사용하게 되어 있는데 

이걸 사용 안할수도 있나요? --> 이 방법을 몰라서 넣어 놓고 있었습니다.

2022-04-16 07:48 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
아하! 애플 기본 이모티콘 인데 음 저는 펑션키로 단축키로 설정해둬 사용합니다.
https://stopoverhere.tistory.com/entry/맥북-이모티콘-Emoji-사용-방법-단축키
요 사이트를 보고 커스텀하게 설정해보실 수 있을것 같아요!

2022-04-16 07:51 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
넵 그건 이해를 했습니다.
다만 현재 Scene/AppDelegate에서 해당 KakaoSDKAuth와 KakaoSDKCommon를 사용하고 있지 않기에 여기서 import를 해주고 실제로 사용되는곳이 없기에 여쭤봤습니다..!

2022-04-16 07:52 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +    UserApi.shared.me { User, error in
아뇨 사용되지 않는다면 _로 축약해서 표현하지 않으면 어떨까해서요!
실제로 인자값을 네이밍해두고 사용되지 않고 있어서 여쭤봤습니다~!

2022-04-16 07:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +      }
아뇨 단순히 궁금했어요!
어떤 기준으로 사용해주시는지 다른 의도가 있었는지 여쭤봤습니다🙌

2022-04-17 07:23 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +import KakaoSDK
넵 수정된 파일에는 사용한 부분으로 옮겨 놨습니다.

2022-04-17 10:56 UTC, closed without merging

2022-04-17 10:56 UTC, Aki-hwang commented
수정 후 다시 PR 올리겠습니다