feat : Add kakao login service
depromeet/mongsil-iOS pull request #26
Opened 2022-04-17 11:02 UTC by Aki-hwang

### Task

1. 애플 로그인 서비스는  아직 구현 중입니다.
2. 카카오 로그인 서비스 구현 중 힌트가 필요해 PR 올립니다.
- KakaoLoginService의  getKakaoUserInfo()에서 eraseToAnyPublisher()로 했음에도 HomeCore에서 아래와 같은 Error가 발생됩니다.
   Cannot convert return expression of type 'AnyPublisher<Void, Never>' to return type 'Effect<HomeAction, Never>
왜 이런 현상이 발생하는지 힌트가 필요합니다.

2022-04-18 02:58 UTC, GREENOVER requested changes
슬랙 채널에서 말씀드렸지만 우선적으로 테스트는 해보지 않았고 코드적인 부분에서만 리뷰를 거쳤습니다!
팀 아이디와 이에 관한 수정들이 이뤄지고나서 실 디바이스 테스트를 해보겠습니다🙏🏻

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    }else{
띄어쓰기 컨벤션을 통일해주면 어떨까요?

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                }
인덴트 컨벤션을 통일해주면 좋을것 같아요🙋🏻

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    print("loginWithKakaoAccount() success.")
테스트 print 구문들은 실제 상용에선 쓰이지 않을테니 없어도 될것 같아요!

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    print(error)
실제 에러가 발생했을때 단순히 print만 해주는게 아닌
이 메서드를 호출한 쪽에서 에러를 받아 처리할 수 있도록 로직을 변경해보면 좋겠습니다..!
한번 이에 대해 어떻게 할 수 있을지 고민해보면 좋을것 같아요~!
아마 이 메서드를 호출하는쪽에서 맵을 사용해 처리해줘야할것같아요.

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +      .fireAndForget()
fireAndForget이 적절할까요?
만약 인증 시 실패가 난다면 getKakaoUserInfo를 불러온 이 액션에서 처리를 해줘야될것 같아서요!
해당 AnyPubliser를 반환받아서 map을 해줘 클로저에서 성공과 실패에 대한 처리가 이뤄져야할것 같습니다🙋🏻

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +//struct AppleLoginView: View {
만약 애플 로그인과 카카오 로그인 PR을 다르게 가져간다고 하면 해당 파일 및 코드들은 제거하고 올려주시면 좋을것 같습니다🙋🏻

2022-04-18 02:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +//  ContentView.swift
KakaoLoginService로 파일명 설명 주석이 변경되야할것 같습니다🙋🏻

2022-04-18 10:41 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    }else{
수정완료 했습니다.

2022-04-18 10:45 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                }
혹시 어느 부분인지 알수 있을까요?

2022-04-18 10:45 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    print("loginWithKakaoAccount() success.")
수정완료했습니다.

2022-04-18 10:48 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                }
전체적으로 4칸 인덴트도 되어있는 부분도 있는것 같습니다..!
예를들어 23 라인도 그렇습니다.
19 라인 시작 부분또한 인덴트가 많이 먹여져 있는것 같습니다.
command + i 로 컨벤션 자동완성을 해줄 수 있습니다.

2022-04-18 10:48 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/AppleLoginService.swift
> +//struct AppleLoginView: View {
수정완료했습니다.

2022-04-18 10:49 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +//  ContentView.swift
수정완료했습니다.

2022-04-18 11:34 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    print(error)
카카오 로그인 버튼을 누르면 아래와 같이 동작하도록 코딩을 수정했습니다.
1. 카카오톡 설치 되어 있는 경우 --> 간편 로그인으로 이동
2. 카카톡 설치되어 있지 않은 경우 --> 웹 로그인으로 이동

2번 상태에서 실패하는 경우 (아이디, 비번 오류 등) 웹 화면에서 실패를 표시해주고 취소를 누르면 카카오 로그인 버튼을 누른 화면으로 돌아옵니다.

즉 카카오 로그인 화면에서 에러에 의한 결과를 보여주고 있는데, 추가로 어떤 내용을 뿌려주면 좋을까요?

2022-04-18 11:36 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +      .fireAndForget()
위에 남겨주신 코멘트랑 비슷한 맥락인 것 같습니다.!!

2022-04-18 11:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                    print(error)
모종의 이유로 알 수 없는 에러에 대해서는 해당 카카오 로그인을 호출한쪽에서 캐치해야될것입니다.
앞으로의 로직을 생각해보면 해당 서비스를 호출하고 성공한다면 추후 들어올 회원가입 API를 호출하는 서비스를 통하게 됩니다. 즉 에러가 발생한다면 이 회원가입 API를 호출하면 안되고 얼럿 혹은 토스트 메시지 같은걸러 실패를 사용자에게 알려줘야합니다.
즉 지금 print error하는 부분은 해당 서비스에서 해주는것이 아닌 해당 서비스를 호출한 액션으로 관심사를 끌고와야합니다.

2022-04-18 11:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Home/HomeCore.swift
> +      .fireAndForget()
네 확인했습니다!
요 부분은 제가 내일 체크해서 예시를 코멘트 혹은 푸쉬해서 보여드려볼께요!

2022-04-18 13:23 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Component/Services/KakaoLoginService.swift
> +                }
혹시나 해서 몇 칸 띄워서 컨벤션 자동완성을 수행 해 변경됨을 확인완료 했습니다.

2022-04-19 02:03 UTC, GREENOVER commented
@Aki-hwang 
혹시 코드 수정이 된건가요~?
재리뷰를 하면 되는지 여쭤봅니다..!
대략적으로 봤을때 코드 많이 깔끔해졌고 몇 부분의 에러 처리와 관련되어 로직만 다듬으면 될것 같다고 보였습니다👍
아 그리고 시뮬레이터로도 카카오톡을 통한 연동은 아니지만 아래 영상과 같이 로그인 할 수 있음은 확인했습니다.
이에 크게 앞으로 작업하고 시뮬레이터로 테스트하는데 지장은 없을거라 생각해요!
<img src="https://user-images.githubusercontent.com/72292617/163905194-e2c64e3d-26f6-4998-9009-c1e855b57e82.gif" width="300" height ="600">

다만 카카오 로그인 시 안내 팝업에서 몽실 밑에 디프만 11기 3조로 되어있어서 요 "디프만 11기 3조" 디스크립션은 없는편이 사용자에게 더 나아보입니다..!
혹시 더불어 하나 궁금한게 지금 이메일(카카오 계정)에 대해서 선택 사항으로 체크할 수 있게 되는데 이를 필수로 설정할 수는 없는걸까요?
사실상 이메일이 선택이라면 회원가입 시 지장이 있을것 같아서요!
(요건 저도 몰라서 여쭤봅니다🙋🏻)
![스크린샷 2022-04-19 오전 10 31 01](https://user-images.githubusercontent.com/72292617/163904986-ea067d73-d19b-4fb4-94b7-2360eb0df5ad.png)

++ 추가로, 커밋 메시지가 모두 동일한것 같아서 구분하기가 쉽지않습니다!
수정된 사항에 대해서는 fix 및 refactor등과 같이 프리픽스를 붙이고 뒤에 해당 작업에 맞는 커밋 메시지를 작성해주시면 감사하겠습니다🙌
++ 만약 수정이 다끝난것이라면 에러 및 결과값을 액션에서 처리하는 부분에 대해서는 아마 처음 접하면 어려우실 수 있으니 별도 시간을 내서 안내드리려 합니다!
p.s.아..! 마지막으로 철진님만 현재 디바이스에서 테스트가 수월함으로 지금 Task였던 카카오 로그인을 하는 전체과정을 실 디바이스에서 진행되는 영상을 녹화해서 공유 해주시길 부탁드립니다🙏🏻

2022-04-19 13:53 UTC, Aki-hwang commented
1. 카카오 로그인 시 안내 팝업에서 몽실 밑에 디프만 11기 3조로 되어있어서 요 "디프만 11기 3조" 디스크립션은 없는편이 사용자에게 더 나아보입니다..!
**--> 어플 이름과 사업자명을 넣게 되어있는데,  어플 이름 : 몽실, 사업자명 : 디프만 11기 3조 -->  어플 이름 : 몽실, 사업자명 : 몽실로 변경 완료했습니다.**

2. 혹시 더불어 하나 궁금한게 지금 이메일(카카오 계정)에 대해서 선택 사항으로 체크할 수 있게 되는데 이를 필수로 설정할 수는 없는걸까요?
사실상 이메일이 선택이라면 회원가입 시 지장이 있을것 같아서요!
**--> 이렇게 선택 동의 항목만 선택이 됩니다. ( 필수 동의 라디오 버튼이 클릭은 되어 있는데 회색처리 되어 있어요)
<img width="634" alt="스크린샷 2022-04-19 오후 10 46 46" src="https://user-images.githubusercontent.com/98097284/164018069-4196b3f4-6e5c-4d82-bbae-66e327f55008.png">**

3. 커밋 메시지가 모두 동일한것 같아서 구분하기가 쉽지않습니다!  
**--> 향후 커밋 메시지를 갈라서 Push 하겠습니다.**

4. 만약 수정이 다끝난것이라면 에러 및 결과값을 액션에서 처리하는 부분에 대해서는 아마 처음 접하면 어려우실 수 있으니 별도 시간을 내서 안내드리려 합니다!
**--> 수정은 완료되었는데 방금 실행을 해보니 주말에 추가한 부분 (KokaoLoginService의 17번째 라인) 때문인지 동의 항목이 안뜨고 바로 넘어가고 있어요. 좀 더 확인을 해봐야 할듯 합니다.**

5. 아..! 마지막으로 철진님만 현재 디바이스에서 테스트가 수월함으로 지금 Task였던 카카오 로그인을 하는 전체과정을 실 디바이스에서 진행되는 영상을 녹화해서 공유 해주시길 부탁드립니다
**--> 제가 영상을 녹화하는건 문제가 없으나, 지금 설정상 우리 모두 실 디바이스에서 실행을 할 수 있습니다. 번들아이디 등록 완료 했고, 네이티브키 역시 코드에 담겨 있거든요. 혹시 실행 해보시고 안되시면 말씀주세요.**

6. 지금 LoginService Brach에만 있는데 찬우님도 이걸 받아서 테스트 해볼수 있는 건가요?


코멘트 감사드립니다.

2022-04-19 14:24 UTC, Aki-hwang commented
카카오에 한번 연결한 경우 서비스를 취소해야만 다시 연결화면을 확인 할 수 있습니다. 

말씀 하신 동영상 송부드립니다.


https://user-images.githubusercontent.com/98097284/164026216-3720a161-7037-40e4-8cba-70bec0cca05e.mp4

2022-04-20 06:33 UTC, GREENOVER requested changes
훨씬 개선되고 이제 거의 완성이 되었네요!
간단한 코멘트 몇개 있습니다~ 그것만 수정해서 푸쉬 부탁드립니다🙏🏻
서비스하고 액션 연계되는 부분은 내일 페어로 같이 진행해보고 해당 PR 머지하시죠..!

2022-04-20 06:33 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
해당 피알 이후에 저희가 작업할때는 None 혹은 개인팀으로 설정해서 테스트하고 PR 시 다시 해당 팀 ID로 원복해야하기에
우선적으로 None으로 팀ID를 설정해두고 작업을 하면 어떨까요?🙋🏻

2022-04-20 06:33 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
요 라인은 왜 추가되었나요~?

2022-04-20 06:33 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Home/HomeView.swift
> +    }
PR시에는 이거 없어도 될것 같아요!
이미 메인에 로그인뷰를 만들어 두어서 이에 연동하면 될것 같습니다.

2022-04-21 09:24 UTC, Aki-hwang commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = LZ887YG4E9;
수정 후 PR 올리겠습니다

2022-04-21 09:26 UTC, Aki-hwang commented on Mongsil/Mongsil/Module/Feature/Home/HomeView.swift
> +    }
수정완료 했습니다.

2022-04-23 05:48 UTC, GREENOVER requested changes
마이너한 하나 리뷰 달았습니다!
해당 리뷰만 반영되면 바로 어프로브하겠습니다~

2022-04-23 05:48 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
요 항목 필요없을것 같아요! 빼도 될것 같습니다!

2022-04-23 05:55 UTC, Aki-hwang commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
제가 추가한 부분이 아니라서.. 혹시 어떤 경우에 저 항목이 들어가는지 알 수 있을까요?

2022-04-23 05:58 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
@Aki-hwang 
아마 디바이스로 사이닝 할 시 오토로 프로비저닝 파일에 대해 서치하도록 다시 중첩되어 설정 항목이 들어간것 같습니다.
코드로 추가해주신 부분은 아닐거구요.
아마 저 항목을 검색해보셔서 제거해주시면 될것 같습니다.

2022-04-23 07:00 UTC, GREENOVER approved these changes
정말 수고 많으셨고 고생하셨습니다! 
머지 해주세요~

2022-04-23 07:05 UTC, merged