feat: add modeltype and mock data
depromeet/mongsil-iOS pull request #42
Opened 2022-04-28 14:55 UTC by MoSonLee

### Task
   - 회원 모델 타입 정의 및 구현
   - 꿈 해몽 모델 타입 정의 및 구현
   - Mock 데이터 assets에 추가

 ### Description
   - 아직 정확한 데이터 타입이 아니므로 임의의 데이터 타입으로 넣어줬습니다.
   - 서버에서 주신 mock데이터 파일이 너무 커서 maincategory -> subcategory -> dream, translate를 보여줄 수만 있으면 되니 그걸 포함하게 두개만 넣어주었습니다.

### Issues
   - Mock 데이터로 디코딩 테스트는 조금 헷갈리는 부분이 있어 진행하지 못했습니다.
   - pull request를 만드는 동안 뭔가 오류가 있어 branch를 많이 만들고 삭제하고 조금 수정된 부분이 있습니다.
      - **그래도 모든 작업을 main이 아닌 branch로 만들어 작업해주었기 떄문에 큰 문제는 없을 것 같으나 혹시나 해서 코멘트 남겨놓습니다!**

2022-04-29 00:53 UTC, GREENOVER requested changes
고생하셨어요!
조금 코멘트가 많을 수 있지만 필수적인 부분이라 남겨봤습니다!
해당 코멘트 토대로 다시 생각해보고 수정해보시면 좋을것 같습니다🙋🏻
또한 해당 스텝에서 JSON mock 데이터로 디코딩 테스트를 해보는건 선택이 아닌 필수일것 같습니다!
이부분도 같이 구현 부탁드려요~🙌

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
JSON 파일로 디코딩 테스트를 하는데 어떤 문제가 있었던건가요?
디코딩 테스트를 하지 않으면 만드신 모델 타입들이 정상적으로 디코딩 되는지 실제 통신을 하기전까지는 올바른지 확인할 길이 없습니다.
또한 통신에서 그걸 테스트하는것은 다른 서버 및 요청 문제일 경우 캐치할 수 없습니다.
해당 PR에서 요 JSON 파일로 만드신 모델에 대해 디코딩을 해보셔야할것 같아요!
또한, 지금 JSON 파일 key value 구조로는 아마 만드신 모델 타입에 매칭이 안될것 같아요.
모델타입에 맞게 JSON 파일을 수정해 사용해보셔야 할것 같습니다!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +//  DreamModel.swift
DreamModel이라는 파일명이 어색합니다!
Dream이라는것 자체가 모델입니다.
Model은 네이밍은 빼도 될것 같아요.

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +}
뭔가 어색하다 했더니 사실 이렇게 나눠도 상관은 없지만 불필요하게 하나의 객체를 더 만드는 느낌이 드네요.
Category 객체는 없어도 될것 같아요.
사실상 이중 선언이 된것 같습니다!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct SubCategory: Codable {
해당 모델 타입들을 한 파일에 담지 않고 별도의 파일로 구분하는게 더 나을것 같습니다.

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let subCategory: [String: [DreamInfo]]
subcategory는 명사로 합성어가 아닌 한 단어입니다.

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let category: Category
명시적으로 코딩키를 넣어주는건 어떨까요?
나중에 해당 모델 타입들에서 연산 프로퍼티들이 생성 될 수도 있고 더 많은 필드들이 들어올 경우가 있을텐데 지금과 같이 자동으로 생성 매핑되게 암묵적으로 선언해두면 헷갈릴 여지가 많습니다!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +//  UserModel.swift
여기도 Model이라는 네이밍이 포함된게 어색해보입니다🥲
없어도 될것 같아요!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
추후 더 편하게 쓰려면 명시적으로 이니셜라이저에서 디코딩을 할 수 있도록 구현이 필요할것 같습니다!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +}
로그인 여부에 대해서 서버에서 넘겨주는것이 없을텐데 필요한걸까요?
만약 로그인 여부를 User 모델에서 프로퍼티로 갖고 있고 싶다면 이 방법 말고 연산 프로퍼티를 사용하는 다른 방법이 있을것 같습니다!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +  let userEmail: String?
userName과 userEmail에서 user는 필요없는 단어이지 않을까요?
이미 이 타입은 User이며 즉 name에 접근한다면 현재와 같은 상황이라면 User.username이 되는것으로 되게 어색해보입니다!
User가 가질 수 있는 프로퍼티인데 중복되는 단어가 들어갈 필요는 없습니다.
간단히 name, email만으로 충분할것 같네요!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +}
위 구현과 이 구현의 차이는 뭔가요?

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct User: Codable {
얘네들도 이니셜라이저를 통해 디코딩을 할 수 있는 선언과 구현이 필요할것 같습니다🙋🏻

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct User: Codable {
유저 모델에 대해 인코딩할때가 있을까요?
만약 필요하다면 자체적으로 encode 메서드를 구현해줘야할것 같고 없다면 인코딩이 없다면
Codable 프로토콜을 따를 필요가 없지 않을까 싶어요!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
꿈 모델에 대해 인코딩할때가 있을까요?
(생각해볼 필요가 있어보입니다!)
만약 필요하다면 자체적으로 encode 메서드를 구현해줘야할것 같고 없다면 인코딩이 없다면
Codable 프로토콜을 따를 필요가 없지 않을까 싶어요!

2022-04-29 00:53 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct userInfo: Codable {
어차피 사라질 객체이긴 할것 같은데 구조체 타입은 소문자로 시작하는것은 Swift 네이밍 컨벤션에 어긋납니다🥲

2022-04-29 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
추가로 이 부분이 무슨말이냐하면
지금 같은 경우 객체에서 자체 이니셜라이저를 통해 디코딩을 해주지 않는다는 가정하에 서버의 실수로 인해 어떤 값을 누락하고 보낼 수 도 있습니다.
클라는 서버에서 내려주는 데이터를 전적으로 믿고 이상이 없다는 가정하에 코드를 구현하면 위험합니다.
서버에서 내려주는 데이터들은 언제든 변할 수 있습니다.
그렇기에 클라에서는 데이터가 들어와야하는데 안들어올 경우도 대비해야합니다.
이에 이니셜라이저로 디코딩을하는 부분을 구현해주면서 기본값에 대해 대비를 해두면 실제적으로 서버에서 누락된 데이터가 있더라도 keyNotFound와 같은 오류를 뱉지 않을 수 있습니다!

2022-04-29 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types
요 레퍼가 도움이 될것 같습니다!

2022-04-29 10:54 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
아아 디코딩 테스트할때 새로운 클래스를 하나 만들어줘서 거기서 print가 되는지만 확인하면 되는 부분일까요?!
또 지금 JSON 파일에서 매칭이 안 되는 문제는 알고 있었는데 목 데이터를 수정할지 아니면 일시적으로 model type만 수정할지가 조금 헷갈렸는데 생각해보니 당연히 mock 데이터만 수정해서 해보면 되겠네요..!
구현해보겠습니다!! 감사합니다

2022-04-29 10:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +//  DreamModel.swift
앗 제 생각으론  Dream이란 이름이 나중에 꿈 기록할 때도 dream이라는 키워드 들어갈테니 조금 구분할 수 있게 넣어줬었는데
dream이라는 정확한 이름은  쓰이지 않을테니 model을 빼서 수정해놓겠습니다!

2022-04-29 10:58 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +}
음 이것을 해준 이유는 나중에 user 하나하나 붙혀주는 것보다 name,  email만 간단히 입력해주면 더 깔끔할거 같아서
구현해봤습니다! 
그냥 선언할 때 이름을 처음부터 name, email로 수정해보겠습니다!

2022-04-29 11:00 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +  let userEmail: String?
아아 위에 리뷰해주신걸 토대로 코드를 수정하다 보니 이것도 덩달아 자연스럽게 해결되네요!
감사합니다

2022-04-29 11:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +//  UserModel.swift
넵 수정했습니다!

2022-04-29 11:02 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +}
다시 생각해보니 필요 없을 것 같아 삭제해주었습니다!

2022-04-29 11:06 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let subCategory: [String: [DreamInfo]]
네 수정해주었습니다!

2022-04-29 11:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +}
수정해주었습니다!

2022-04-29 11:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct SubCategory: Codable {
이 부분은 잘 이해가 되지 않습니다..! ㅜㅜ  현재 이렇게 해준 상태입니다.!
<img width="360" alt="image" src="https://user-images.githubusercontent.com/77050826/165934047-520f90bd-1dda-4b9d-82de-6c2f06d4cf69.png">

2022-04-29 11:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let category: Category
<img width="360" alt="image" src="https://user-images.githubusercontent.com/77050826/165934104-048ea021-6422-499b-82d4-8715cbe23921.png">

이렇게 임의로 코딩키를 넣어주었습니다..! 괜찮을까요?!

2022-04-29 11:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct User: Codable {
<img width="236" alt="image" src="https://user-images.githubusercontent.com/77050826/165934238-c2611b7b-52a9-4d8f-be18-2b58aecfee13.png">
아 제가 모델 타입을 많이 지정해보지 않아서 일단 모두 Codable로 선언해주었었네요..!
필요가 없다고 생각되어 Decodable로 수정해주었습니다.!

2022-04-29 11:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
위 user와 같은 맥락이네요.! Decodable로 수정해주었습니다!

2022-04-29 11:18 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct userInfo: Codable {
앗 실수했네요 삭제해주었으니 다음부터 더 신경쓰겠습니다! 감사합니다

2022-04-29 11:28 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct Dream: Codable {
무슨 말씀인지 이해했습니다.!!
모든 객체내부에 Codingkeys, 디코딩을 할 수 있는 이니셜라이저를 추가해주었습니다..!

2022-04-29 11:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/UserModel.swift
> +struct User: Codable {
수정해주었습니다.!

2022-04-29 11:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct SubCategory: Codable {
네네 각 구조체들을 다른 파일로 구분해줄 수 있지 않나요??

2022-04-29 11:40 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let category: Category
네네 그런데 각 카테고리가 키값도 카테고리면 같으니 별도로 넣어줄 필요는 없이 단순히 선언만 해주면 됩니다!

2022-04-29 11:45 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +  let category: Category
수정해주었습니다!

2022-04-29 11:49 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamModel.swift
> +struct SubCategory: Codable {
<img width="219" alt="image" src="https://user-images.githubusercontent.com/77050826/165938730-c26721cb-fe3d-4cb9-b872-81478e821e29.png">
요렇게 나눠서 구현해 주었습니다..!
Class가 많아지는 것보다 하나에 넣어주는게 파일이 덜 무거워져서 좋다고 생각했는데 아니었나보군요..!

2022-04-29 13:25 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
<img width="700" alt="image" src="https://user-images.githubusercontent.com/77050826/165952465-fb085f4a-84dc-45ea-8179-702094a055f3.png">
   - mock 데이터를 디코딩 테스트하는 코드가 조금 헷갈리네요.. 일단 에러는 안 뜨는데 출력은 안되고 있습니다..! ㅜㅜ
   - 혹시 코드적으로 문제가 있을까요? 레퍼를 이것저것 찾아보고 있긴합니다..!

2022-04-29 13:47 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
현재 스유기반인데 해당 뷰를 어떻게 로드해주는지 감이안옵니다! 추가로 인코딩은 왜해주는걸까요..?

2022-04-29 13:47 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
음.. 전체적으로 디코딩을 이해하는 기초적인게 필요할것 같습니다!

2022-04-29 14:02 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Assets/mock.json
> +  "신체": {
아아 그냥 뷰는 대충 잡아만 놓고 아직 띄워주진 않은거라 수정 예정이었습니다..!! 그냥 임의로 스위프트 파일로 만들어본거라..!
맞습니다..디코딩 개념이 조금 부족한거 같습니다..디코딩을 조금 학습해보겠습니다..!

2022-05-01 23:20 UTC, GREENOVER requested changes
고생많으셨습니다!
훨씬 나아졌고 이제 거의 완성되었네요..!
기능 문제가 아니라 사소한 컨벤션에서 맞출 부분이 있어 코멘트 남겼습니다~!
해당 코멘트들만 수정되면 좋을것 같습니다🙏🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		774F78AE281EB89C00863070 /* PrintMockView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = PrintMockView.swift; sourceTree = "<group>"; };
JSON 테스트 결과 확인했습니다!
고로 메인에 머지될때는 해당 파일과 관련되어 불필요한 파일은 없어도 될것 같아요🙋🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Assets/Mock/PrintMockView.swift
> +}
잘해주셨네요!
확인되어서 이제 해당 파일 관련들은 삭제 부탁드립니다🙏🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +  let category: [String: [Subcategory]]
보통 프로퍼티 선언 다음에 이니셜라이저가 옵니다🙋🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamInfo.swift
> +  let description: String
요기도 마찬가지로 프로퍼티 선언 다음에 이니셜라이저가 오는게 적절할것 같습니다🙋🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +struct Dream: Decodable {
추후 모듈화를 위해 타입과 이니셜라이저 그리고 프로퍼티/enum을 퍼블릭하게 접근 제어를 설정하면 더 좋을것 같아요!

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Subcategory.swift
> +  let subcategory: [String: [DreamInfo]]
여기도 마찬가지로 순서를 바꾸면 좋겠습니다..!

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +import Foundation
한줄 띄우는게 다른 컨벤션과 맞아보입니다🙋🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +import Foundation
한줄 띄우는게 다른 컨벤션과 맞아보입니다..!

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +  }
name과 email은 옵셔널 값으로 해당 이닛에서 옵셔널에 대해 초기값을 주면 어떨까요?
그렇지 않다면 추후에 호출하는쪽에서 처리해줘야하는데 번거로울 수 있습니다..!
`decodeIfPresent`로 해보시면 처리해볼 수 있을겁니다🙋🏻

2022-05-01 23:20 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +            .renderingMode(.template),
이친구는 왜 들여쓰기가 바뀌었을까요??

2022-05-02 01:40 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Assets/Mock/PrintMockView.swift
> +}
넵 삭제해주었습니다!

2022-05-02 01:42 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +		774F78AE281EB89C00863070 /* PrintMockView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = PrintMockView.swift; sourceTree = "<group>"; };
넵!

2022-05-02 01:47 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +  let category: [String: [Subcategory]]
수정해주었습니다!

2022-05-02 01:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +import Foundation
수정해주었습니다!

2022-05-02 01:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamInfo.swift
> +  let description: String
수정해주었습니다!

2022-05-02 01:49 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Subcategory.swift
> +  let subcategory: [String: [DreamInfo]]
수정해주었습니다!

2022-05-02 01:50 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabView.swift
> +            .renderingMode(.template),
앗... 수정해주었습니다..!

2022-05-02 01:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +struct Dream: Decodable {
이니셜라이저에서는 private 대신 fileprivate를 써주는게 맞는건가요?!

2022-05-02 02:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +  }
<img width="330" alt="image" src="https://user-images.githubusercontent.com/77050826/166176424-caeb34d4-bb9e-4e11-8cd2-0494691447e0.png">
이렇게 수정해주었습니다!

2022-05-02 02:15 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +struct Dream: Decodable {
아뇨! 다 퍼블릭하게 해야되지 않을까요~?

2022-05-02 02:24 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +struct Dream: Decodable {
정신이 나갔나 봅니다.. public으로 밖에서도 써야지 하면서 private을 치고 있었네요.. 
해결했습니다!

2022-05-02 02:36 UTC, GREENOVER requested changes
동일한 public 접근제어 관련 코멘트 남겼습니다!
이 부분만 수정되면 머지해도 될것 같아요👍

2022-05-02 02:36 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +  private let category: [String: [Subcategory]]
이 프로퍼티도 public해야 합니다🙋🏻

2022-05-02 02:36 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DreamInfo.swift
> +struct DreamInfo: Decodable {
하위 타입들도 전부 public해야 합니다🙋🏻
독립적으로 디코딩을 할 수 있어야하고 테스팅이 되어야합니다~!

2022-05-02 02:36 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Subcategory.swift
> +struct Subcategory: Decodable {
하위 타입들도 전부 public해야 합니다🙋🏻
독립적으로 디코딩을 할 수 있어야하고 테스팅이 되어야합니다~!

2022-05-02 02:36 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +struct User: Decodable {
이 타입도 public해야 합니다🙋🏻

2022-05-02 02:45 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/User.swift
> +struct User: Decodable {
수정해주었습니다!

2022-05-02 02:45 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Subcategory.swift
> +struct Subcategory: Decodable {
수정해주었습니다!

2022-05-02 02:46 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DreamInfo.swift
> +struct DreamInfo: Decodable {
수정해주었습니다!

2022-05-02 02:46 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Dream.swift
> +  private let category: [String: [Subcategory]]
수정해주었습니다!

2022-05-02 02:47 UTC, GREENOVER approved these changes
고생 많으셨습니다!
머지 부탁드립니다🙌

2022-05-02 02:47 UTC, merged