feat: record initial view
depromeet/mongsil-iOS pull request #54
Opened 2022-05-13 16:58 UTC by MoSonLee

### Task
   - reocrd view 초기 구현</br>
 
### Description
   - alertmodal 버튼색상  선택시 msred로 할시 오류가 나서 red로 일단 바꿔뒀습니다.!</br>
   - backbutton이 arrow 일 때와 canclicon일 때 가 달라서 layout이 약긴간 틀어지는데 msnavigation과 관련된 버튼쪽들을 건드려야할거 같아서 우선 맞춰주지 않았습니다.!</br>
   - rightbuttontext의 font는 지금 pretendard인데 다른 것으로 바꾸신다고 하셔서 임의로 TItile1으로 설정해주었습니다!</br>

2022-05-13 22:16 UTC, GREENOVER requested changes
@MoSonLee 
우선 상세 코드 리뷰 전 기능 테스트에서 질문 및 고쳐야할 사항이 있어 수정 요청드립니다.
1. 아래 사진과 같이 2,000자를 채우는 과정에서 글자수가 많아지면 저렇게 영역이 짤려 보이게 됩니다. 수치를 유동적으로 될 수 있게 조정해주셔야할것 같습니다.
![스크린샷 2022-05-14 오전 7 00 57](https://user-images.githubusercontent.com/72292617/168395082-a4ee849a-30ca-4cf2-92ff-fc15a368a27c.png)
2. 캘린더 부분인데요, 이 부분 저렇게 디자인 가기로 디자인팀하고 협의를 하신 부분일까요? 확인 한번 해주셔야할것 같습니다.
또한 바텀시트가 safeArea에서 뜨고 있는데 보관함쪽 보시면 인디케이터 bottom 부분에서부터 잡히는것이 디자인 요구이기에 맞춰줘야합니다.
요 부분 보관함쪽 구현보시면서 처리하시면 됩니다.
![스크린샷 2022-05-14 오전 7 01 14](https://user-images.githubusercontent.com/72292617/168395320-82534ed9-fca0-43ec-a47e-a26c6a33869e.png)
3. msRed 색상에는 문제가 없습니다. 
아마도 추측하기에 에셋 파일 명이 잘못들어가있던지 그랬을것 같습니다. 요 부분 만약 수정이 필요하시다면 수정을 해주시면 됩니다.
디자인에서 요구한 msRed 색상을 사용하는 방향이여야 할것 같습니다.
5. 네비게이션바의 레이아웃이 틀어진다는게 어떤 말씀인지 모르겠습니다.
아래 캡쳐 이미지로 보면 틀어진 부분이 어딜까요?
혹시 해당 스레드와 관련있는것인지 한번 확인해주시면 좋을것 같아요.
https://depromeet11.slack.com/archives/C037LG0M2GN/p1652407696886719
![스크린샷 2022-05-14 오전 7 08 39](https://user-images.githubusercontent.com/72292617/168395528-26b4b6b3-6bc1-45a4-a32f-d80e8b37455a.png)
추가로, 네비게이션바의 좌우 패딩이 요구한 디자인과 다릅니다.
요 부분 맞춰주셔야 될것 같아요!
코드에서 backButton등의 패딩을 주지 않으셔도 됩니다. 제가 건드려놔서 그냥 네비게이션 바를 사용하는곳에서 네비게이션 바 자체에 패딩으로 조절해주시면 될것 같아요. (보관함쪽에서 어떻게 사용되었는지 보시면 좋을것 같습니다.)
6. 글자 수 초과 시 토스트 메시지가 노출되지 않고 있습니다. 구현이 필요해보입니다!
 ***
요 부분 기능적인 이슈 수정 부탁드립니다!
그 후에 코드 리뷰 하는게 맞을것 같습니다🙏🏻

2022-05-14 15:54 UTC, MoSonLee commented
### 2차 수정 
   - 캘린더 height 수정</br>
   - mainTextField, titleTextField layout 수정</br>
   - 디자인 팀에게 여쭤봤을때 titleText도 줄바꿈을 원하셔서 titleText도 수정</br>
   -  datepicker가 present될 때 뒤를 블러 처리 + countttilte이 동시에 나오는 곳에서 오류 발견 -> 수정 완료 </br>
      - 줄바꿈을 사용하기 위해 textField 아닌 textEditor를 사용했습니다</br>
   -  keybord defult로 tilte로 띄워줬습니다.( 디자인팀에서 아직 메인쪽에 띄울지 title 쪽을 default로 잡을지 고민중이신듯해서 일단 title로 잡아줬습니다 -> 나중에 바꿔달라하셔도 간단하게 수정 가능합니다!)</br>
 
### issues
   - rightbutton 활성화 관련 issue를 발견했습니다.</br>
   - rightbutton disabled가 정말 정말 도저히 되지 않아 일단 다른 부분부터 코드 올려놨습니다ㅜㅜ</br>
   - 이쪽 부분이 시간을 정말 너무 많이 잡아 먹어서 ㅜㅜ 한번 여쭈어보고 싶은데 시간이 늦어서 내일 한번 여쭤봐도 괜찮을까요..? ㅜㅜ</br>

2022-05-15 01:17 UTC, GREENOVER requested changes
@MoSonLee 
Right Button 활성화 이슈가 무엇인가요?
어떤 이슈였는지 같이 기재해주시면 저도 파악하는데 도움될것 같아요..!
(이슈라면 빠르게 해당 MSNavigationBar를 수정해야하니까요ㅠ)
우선 마찬가지로 코드 리뷰 전 기능 및 디자인에 대해 여쭤볼게 있습니다.
말씀하신 RightButton disabled 제외하고 입니다.
1. 아래 title의 폰트 및 영역 사이즈가 피그마 디자인과 전혀 달라 보입니다.
모든 디자인 레이아웃은 피그마와 맞춰주세요ㅠ
전체적으로 PR전 기능뿐 아니라 디자인 체크도 다 해주시면 좋겠습니다.
(위가 작업하셨던 레이아웃, 아래가 피그마 레이아웃입니다.)
<img width="323" alt="스크린샷 2022-05-15 오전 9 56 07" src="https://user-images.githubusercontent.com/72292617/168453091-63bf44b1-a809-4cf3-8192-85fbe6a21bbb.png">
<img width="291" alt="스크린샷 2022-05-15 오전 9 56 18" src="https://user-images.githubusercontent.com/72292617/168453094-0a94f269-1b30-4a09-a189-be46bbb3126f.png">
2. 얼럿 관련하여 레이아웃이 안맞습니다.
얼럿 노출 시 좌우 패딩을 보시면 얼럿이 중앙에 오지 않고 있습니다.
아마도 해당 얼럿의 노출 뷰가 contentsextView에서 노출되기에 그렇게 된것 같아요.
recordView 전체 위에 얼럿이 노출되야 할것 같습니다.
<img width="372" alt="스크린샷 2022-05-15 오전 9 56 58" src="https://user-images.githubusercontent.com/72292617/168453120-0a958ec1-8eee-4648-899d-b99cbe1239ef.png">
3. 얼럿 노출 View에 관해서 2번 코멘트와 더불어 얼럿이 노출 시 title 및 네비게이션 바등에 대해서는 비활성화 느낌이 들지 않습니다. 즉 opacity가 조절되지 않아보여요.
이 부분은 2번 코멘트에서 말했듯 alert 노출 View가 content에만 적용되어 있는것 같아 보이네요.
수정이 필요합니다.
아마 얼럿이 떠있을때도 title의 수정및 navigation 뒤로가기등은 활성화되어 title 텍스트 기입도 되고 버튼도 눌릴겁니다.
이슈입니다.
![Simulator Screen Shot - iPhone 11 - 2022-05-15 at 09 57 26](https://user-images.githubusercontent.com/72292617/168453240-008a1213-0a16-4114-a935-0f5c5f63436c.png)

4. 키보드 타입에 대해 수정이 필요할것 같아요.
현재 키보드에서는 확인/다음과 같은 버튼이 없기에 title을 쓰다가 content를 쓰고싶으면 직접 해당 영역을 터치해 새 키보드를 노출시켜야합니다.
그런데 아마 다른 앱도 쓰시면서 느끼셨을것처럼 키보드에서 확인과 같은 버튼이 있어서 누르면 자동으로 다음 텍스트로 매칭되고 이어서 쓸 수 있는 것이 있습니다.
이 부분은 keyboard Type에 대해 어떤것들이 있고 우리가 필요한 키보드 타입이 무엇인지 한번 생각해보시고 구현한다면 좋을것 같습니다.
***
우선 디자인 및 기능에서 리팩토링할 부분이 있어 아직 코드 리뷰는 하지 않았습니다!
RightButton disabled 관련 사용은 내일 저녁에 같이 말씀해보시고 이외 코멘트 드린 부분은 수정 부탁드립니다.

2022-05-16 16:50 UTC, MoSonLee commented
### Task
   - checktextcount가 키보드 위로 올라오게 조정했습니다!.</br>
      - 가져온 함수를 최대한 이해해 보고 조정해야할 부분을 찾아서 고쳐주었습니다.</br>
   - 전반적인 layout 모두 수정 후 맞춰주었습니다..! (제일 작은기기부터 큰 기기 모두 해봤는데 이상은 없는 것 같습니다.)</br>
   - dateTitle View를 오버레이 시킨걸 삭제하고 msnavigaitonbar를 사용하여주었습니다.</br>
   - nextbuttonabled 액션을 처리해주었습니다.</br>

### Issues
   - **tilteText쪽에서 texteditor을 사용하면 lineLimit가 사용이 안 되는 오류를 발견했습니다.**</br>
   - 피그마로 디자인팀에게 말씀 드렸습니다.! (history에 영희님이 작성해주셨습니다!) </br>
   - 제가 구현을 못 하는 거일 수도 있는것 같습니다.! ㅜㅜ  시도를 여러방면으로 해봤는데 textEditor쪽에 개행을 할시 scroll을 막아주고 lineLimit를 걸어주려했는데 lineLimit가 textEditor쪽에서 작동되질 않았습니다.ㅜㅜ!</br>
 
### Solution
   - 제목이 40자까지 필요없을거 같다고 하셔서 -> 제목 최대 20자 + 개행 안됨으로 수정해주었습니다.</br>
   - 20자면 딱 타이틀에 맞아서 개행이 필요가 없었습니다!</br>

2022-05-17 03:09 UTC, GREENOVER requested changes
@MoSonLee 
고생하셨습니다!
전체적으로 훨씬 많이 나아졌네요👍
일단 RecordKeyword View/Core 쪽은 관심사 밖이라 리뷰 하지 않았습니다.
우선적으로 레이아웃이 전체적으로 많이 다듬어지긴 했지만 피그마와 여전히 수치가 다른 부분들이 좀 있는것 같습니다.
전체적으로 리뷰 토대로 코드를 돌아보면서 불필요한 구현들은 날리고 수치도 다시 한번 피그마와 전체적으로 체크해주시면 좋을것 같습니다!

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Views/Buttons/RightButton.swift
> +        .foregroundColor(.gray2)
오 놓쳤던 부분인데 수정 감사합니다👍

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +  public var closeButtonAlertModel: AlertDoubleButtonState?
이 프로퍼티 더이상 안쓰이는것 같아요!
관련된 코드들은 전부 제거되어도 될것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +import SwiftUI
Core에서 SwiftUI 라이브러리 임포트가 필요한 이유가 어떤걸까요??

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var closeButtonAlertModal: AlertDoubleButtonState?
closeButtonAlertModal 네이밍은 닫기버튼얼럿모달인데 저희가 지금까지 얼럿모달 네이밍으로 칭한 부분들은 전부 어떤 얼럿 모달인지에 대해 내포하고 있었습니다.
즉 네이밍 수정이 필요해보여요..!
예를들어 cancelRecordAlertModal과 같은 느낌이 있을것 같아요.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +    return  convertDateToString(currentDate)
return과 conver~~ 사이 한칸 더 띄워져 있으며 사실상 연산 프로퍼티 특성에서 이럴경우 return은 필요 없습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var isDisplayDatePicker: Bool = true
이 프로퍼티 어디서 사용되나요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var closeButtonTapped: Bool = false
이 프로퍼티 어디서 사용되나요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var closeButtonAlertModal: AlertDoubleButtonState?
추가로 얼럿도 ChildState입니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  case textTyped(Bool)
해당 액션 사용되나요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  case closeButtonAlertModal(AlertDoubleButtonAction)
위 alertModal 프로퍼티가 변하면 따라서 이 액션의 케이스명도 변할 수 있겠네요!

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  }
간단히 `return text.count > upper ? false : true`로 나타내면 깔끔할것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      }
불필요한 액션인것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      if abled == true {
`state.local.isNextButtonAbled = abled ? true : false`
로 표현하면 어떨까요?
아주 간단한 분기문인데 5~6줄이 되다보니 가독성이 떨어지고 코드 양이 늘어나게 됩니다.
성능은 같은데 말이죠ㅠ

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        }
얘네 코드가 사실상 아래 mainTextFieldChanged에서도 중복되는 코드 같은데 이걸 하나의 private한 메서드로 만들어 처리해주면 어떨까요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      if checkTextCount(text: text, upper: 25) {
title 20자 제한아닌가요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +import Combine
필요하지 않은 임포트인것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      MsNavigationView(store: store)
MS는 고유명사처럼 저희가 쓰고 있어서 MS 대문자로 네이밍하는것이 맞을것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +            backButtonAction: {ViewStore(store).send(.isCloseButtonTapped(true))},
{와 ViewStore사이 한칸 띄워주세요..!

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +            titleButtonAction: { ViewStore(store).send(.navigationBarDateButtonTapped)
{ 뒤에 View~ 선언부를 개행해서 사용해주세요.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +    ZStack {
ZStack 필요한가요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +          Spacer()
HStack Spaer 필요한가요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +  @State private var becomeFirstResponder = false
이 State 프로퍼티 어디서 사용되나요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .foregroundColor(.gray3)
내용 기입시 컬러는 gray2로 피그마에 표기되어 있는것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .foregroundColor(.gray3)
font 즉 title3에 대한 설정이 누락되었습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        Text("제목 (최대 20자)")
플레이스 홀더 즉 여기에서 Text 색상을 gray8을 주어야할것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .opacity(titleTextViewStore.state.isEmpty ? 0.25 : 1)
opacity 조건은 더이상 필요없지 않을까요?
디자인에 나온 수치도 아닌 임의로 잡아주었기에 더욱 필요없을것 같습니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .frame( maxHeight: 36, alignment: .trailing)
(와 maxHeight 사이 빈칸 공백 제거해주세요.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .frame( maxHeight: 36, alignment: .trailing)
36이라는 맥시멈 높이 수치는 어디서 나온것이며 trailing의 조건은 왜 필요한가요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        }
실제적으로 잘 작동되시나요?
즉 기록하기로 넘어갔을때 자동으로 키보드가 나타나는건지 궁금해요.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +          TextEditor(text: $placeholederText)
이 색상은 gray8로 설정되야하지 않을까요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        .foregroundColor(.gray3)
font body2 설정이 필요해보입니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        .opacity(mainTextViewStore.state.isEmpty ? 0.25 : 1)
필요없을것 같아요.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +          Text("\(num)/2000")
Text가 중복되어 선언되다보니 onKeyboard 메서드 호출도 중복되는것 같은데
text를 받아 0이면 nnnn, 글자수가 있으면 \(num)이 구현을 하나의 변수로 만들고 사용해서 코드 재사용을 줄이면 어떨까요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      VStack {
VStack 필요한가요?

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +  init(store: Store<WithSharedState<RecordState>, RecordAction>) {
한줄 띄워주세요..!

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +}
공통적으로 View를 extension하는것이면 별도 Module > Component > Extensions > View > View+extensions 파일이 만들어져 있습니다.
이 파일안에서 해당 메서드들을 위치시키는게 적합해보입니다.

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
>  }
별도 파일로 분리해서 사용해주세요!

2022-05-17 03:09 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .animation(.easeInOut(duration: 0.33))
iOS 15에서 이런 사용이 deprecated 되었습니다.
Xcode에서도 분명 warning 메시지를 띄워줬을거에요. 
수정이 필요해보입니다.

2022-05-17 05:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/MainTab/MainTabCore.swift
> +  public var closeButtonAlertModel: AlertDoubleButtonState?
수정완료해주었습니다.!

2022-05-17 05:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +import SwiftUI
수정해주었습니다.!

2022-05-17 05:18 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var closeButtonAlertModal: AlertDoubleButtonState?
수정해주었습니다!

2022-05-17 05:18 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +    return  convertDateToString(currentDate)
수정해주었습니다.!

2022-05-17 05:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var isDisplayDatePicker: Bool = true
아 수정해주었습니다.!

2022-05-17 05:20 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  public var closeButtonTapped: Bool = false
수정해주었습니다.!

2022-05-17 05:20 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  case textTyped(Bool)
수정해주었습니다.!

2022-05-17 05:23 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  case closeButtonAlertModal(AlertDoubleButtonAction)
수정해주었습니다!

2022-05-17 05:24 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +  }
넵 수정해주었습니다!

2022-05-17 05:24 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      }
넵 삭제해주었습니다!

2022-05-17 05:25 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      if abled == true {
수정해주었습니다!

2022-05-17 05:39 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      if checkTextCount(text: text, upper: 25) {
수정해주었습니다!

2022-05-17 05:39 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +import Combine
수정해주었습니다!

2022-05-17 05:40 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +            backButtonAction: {ViewStore(store).send(.isCloseButtonTapped(true))},
수정해주었습니다!

2022-05-17 05:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +            titleButtonAction: { ViewStore(store).send(.navigationBarDateButtonTapped)
수정해주었습니다!

2022-05-17 05:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +    ZStack {
수정해주었습니다!

2022-05-17 05:42 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +          Spacer()
수정해주었습니다!

2022-05-17 05:47 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      MsNavigationView(store: store)
수정해주었습니다!

2022-05-17 05:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .foregroundColor(.gray3)
수정해주었습니다!

2022-05-17 05:49 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .foregroundColor(.gray3)
수정해주었습니다!

2022-05-17 05:50 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        Text("제목 (최대 20자)")
수정해주었습니다!

2022-05-17 05:52 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .opacity(titleTextViewStore.state.isEmpty ? 0.25 : 1)
삭제해주었습니다!

2022-05-17 05:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      VStack {
삭제해주었습니다!

2022-05-17 05:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +  init(store: Store<WithSharedState<RecordState>, RecordAction>) {
수정해주었습니다!

2022-05-17 05:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +}
수정해주었습니다!

2022-05-17 05:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
>  }
수정해주었습니다!

2022-05-17 05:59 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .frame( maxHeight: 36, alignment: .trailing)
frame쪽 삭제해주었습니다!

2022-05-17 06:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        .foregroundColor(.gray3)
수정해주었습니다!

2022-05-17 08:05 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +  @State private var becomeFirstResponder = false
삭제해줬습니다!

2022-05-17 08:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        }
<img width="632" alt="image" src="https://user-images.githubusercontent.com/77050826/168766246-50c7205f-ff05-4b84-82cc-9bbc269bb4dd.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/77050826/168766303-142bd08f-512c-422b-a254-f6582255bd38.png">

찬우님 이렇게 선언해봤는데 큰 의미가 없는 것 같아서 bool타입을  반환하는 것이 아닌
 메소드에서 Effect를 반환시키켜 구현하는 방향을 말씀하신건가요?!

2022-05-17 08:49 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +      .animation(.easeInOut(duration: 0.33))
수정해주었습니다!

2022-05-17 08:51 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        }
넵 잘 작동하는거 확인했습니다! 
실행화면 첨부합니다 xcode simulator에서 toggle keybord를 활성화 시킨후에 하면 보이더라구요!

![Simulator Screen Recording - iPhone SE (3rd generation) - 2022-05-17 at 17 50 11](https://user-images.githubusercontent.com/77050826/168770889-7a999fb7-6cdc-4c12-9bec-8c0ee721add8.gif)

2022-05-17 08:52 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +          Text("\(num)/2000")
수정해주었습니다!

2022-05-17 09:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        .opacity(mainTextViewStore.state.isEmpty ? 0.25 : 1)
<img width="620" alt="image" src="https://user-images.githubusercontent.com/77050826/168772593-580e52a4-67d9-41e2-a9a3-aca4cefaf321.png">
![image](https://user-images.githubusercontent.com/77050826/168772636-5443fa8b-235c-486b-9a47-8d8957aa4908.png)

강제적으로 opacity를 활성화 시켜주지 않으면  placeholder 텍스트가 보이지 않습니다.!
아마 texteditor에 placeholder가 사용이 안되어 강제적으로 placeholder을 넣어주기 위해서 사용한 코드라서 opacity를 지우면 
Placeholder쪽 텍스트가 보이지 않는것같습니다. ㅜㅜ

2022-05-17 09:03 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        }
음 의미가 없다는게 어떤 말씀인지 잘 모르겠습니다!
이미 저 메서드 하나의 구현으로 2개의 액션에서 동일한 로직을 줄여주지 않았나요?
저는 첫번째 캡쳐된 방식을 의미했습니다.

2022-05-17 09:04 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        }
음 제가 캐시 날리고 다시 해볼께요!
키보드 토글도 하고 여러가지 해봤는데 안되었던것 같아서요😅

2022-05-17 09:06 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        }
아하 생각해보니 empty를 판별해주는 로직을 줄여주었군요!
넵 수정해주었습니다 감사합니다!

2022-05-17 09:08 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        }
앗 이건 제가 잠시 테스트로 위로 함수를 위에 뷰에 사용하고 pr을 실수로 올렸었네요 ㅜㅜ
수정해놨습니다.! 다음 pr에선 정상적으로 보이실거예요 ㅜㅜ 혼란을 드려 죄송합니다

2022-05-17 09:08 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordView.swift
> +        .opacity(mainTextViewStore.state.isEmpty ? 0.25 : 1)
아아 이해했습니다!

2022-05-17 10:11 UTC, MoSonLee commented
### 코드 수정
   - 코드 리뷰를 토대로 layout 및 코드를 refactoring 해주었습니다.!

2022-05-17 11:19 UTC, GREENOVER requested changes
고생하셨습니다!
정말 마이너한 4가지 정도만 코멘트 남겼습니다.
이 부분만 수정되면 더이상 현재 리팩토링할건 안보이는것 같습니다!

2022-05-17 11:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        return Effect(value: .presentToast("꿈일기는 최대 2000자까지 작성할 수 있어요."))
피그마에서는 꿈 일기로 띄어쓰기가 있는것 같은데 혹시 의논하셨던게 있을까요?
없다면 맞춰줘될것 같습니다!

2022-05-17 11:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +    closeButtonAlertModel: AlertDoubleButtonState? = nil,
파라미터 인자 네이밍이 바뀌지 않았습니다.

2022-05-17 11:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +private func checkTextFieldEmpty(titleText: String, mainText: String) -> Bool {
state 자체를 inout 파라미터로 받아온다면 해당 파라미터 시그니쳐와 호출하는쪽에서도 인자가 깔끔해질것 같아요~!

2022-05-17 11:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      state.local.isNextButtonAbled = abled ? true : false
생각해보니 이거 삼항연산자까지도 필요없을것 같습니다.
state.local.isNextButtonAbled = abled로 끝날것 같아요.

2022-05-17 11:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +      state.local.isNextButtonAbled = abled ? true : false
수정해주었습니다!

2022-05-17 11:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +        return Effect(value: .presentToast("꿈일기는 최대 2000자까지 작성할 수 있어요."))
수정해 주었습니다!

2022-05-17 11:30 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +    closeButtonAlertModel: AlertDoubleButtonState? = nil,
앗 refactor -> rename을 했는데 이게 안 바뀌었네요 ㅜㅜ 다음부턴 하나씩 바꿔보도록 하겠습니다!

2022-05-17 12:09 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +private func checkTextFieldEmpty(titleText: String, mainText: String) -> Bool {
넵 수정해주었습니다!

2022-05-17 12:13 UTC, MoSonLee commented
최종 수정 완료 후 pr 올렸습니다!

2022-05-17 12:24 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
> +private func checkTextFieldEmpty(titleText: String, mainText: String) -> Bool {
혹시 제가 한 방향이 맞는걸까요..?

2022-05-17 12:29 UTC, GREENOVER requested changes
구현이 잘못된 부분이 있어 코멘트 드립니다!

2022-05-17 12:29 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
>  }
음 state 자체를 인자로 받아보시면 좋을것 같아요!
지금 현재 수정된 부분으로는 파라미터 호출 시그니쳐가 줄거나 하지 않았어요.
지금 해주신건 단순 inout만 해주신거라 별 의미가 없습니다.
inout이 어떤건지 어떻게 사용되는지를 먼저 이해를 해볼 필요가 있을것 같아요.
그다음 RecordState 자체를 받아 사용할 수 있도록 해보면 어떨까요.

2022-05-17 13:03 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
>  }
![image](https://user-images.githubusercontent.com/77050826/168816759-a3801854-e473-435d-bcdf-129abfaced85.png)

사용부
![image](https://user-images.githubusercontent.com/77050826/168816994-cea1c5cb-3047-451c-87f1-bd3396fe0516.png)

로 수정해주었습니다 inout은 말 그대로 안에서 사용하기 위해 선언한건데 처음에 해준건 아무의미가 없었네요 ㅜㅜ
혹시 이렇게 구현하는게 맞을까요?!

2022-05-18 00:58 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Record/RecordCore.swift
>  }
넵 inout 사용은 맞습니다!
조금 더 보완되면 좋을점은 제가 코드로 올려보겠습니다!

2022-05-18 01:19 UTC, GREENOVER approved these changes
@MoSonLee 
고생 많으셨습니다!
제가 마지막 커밋으로 코드 컨벤션을 조금 잡았어요.
큼직하게는 액션들의 순서를 맞춰줬으며 state inout에 대해서 조금 수정했습니다.
그 부분 말고 현재 기능에서 한가지 크리티컬하게 보일 수 있는 이슈가 있습니다.
아래 영상과 같이 키보드가 올라올때 mainTextEditor 영역이 따라 올라가진 않습니다.
그게 왜 문제냐 하면 영상을 보면 아시겠지만 쭉 타이핑을 많이 했다고 가정한다면 키보드 영역을 침범해서 타이핑 되는 글씨들은 쓰고 있는 도중에 보이지 않게 됩니다.
요 부분은 수정이 되야할것 같아요.
우선 현재 PR 볼륨이 커져서 머지하겠습니다!
해당 관련해서만 이슈를 하나 만들어 할당 드리겠습니다.
그 부분 진행해주시면 될것 같아요..!
https://user-images.githubusercontent.com/72292617/168937558-7c2f6d4c-77ee-4530-881a-d015099052fd.mp4

2022-05-18 01:19 UTC, GREENOVER commented
@MoSonLee 
코멘트 확인 되시면 머지 눌러주세요🙌

2022-05-18 01:33 UTC, merged