feat: settingView and core
depromeet/mongsil-iOS pull request #64
Opened 2022-05-24 07:28 UTC by MoSonLee

### Task
   - settingView and core 구현 및 refactor</br>

### Description
   - makers 뷰는 이미지 + 원하는 페이지 입력해주시면 변경 가능하게 구현했습니다.(찬우님이 만들어주신 diarycardView를 사용해주었습니다.)</br>
   - 로그아웃, 회원탈퇴 로직 구현 완료했습니다</br>
   - 서버팀에서 주는대로 statuscode를 String -> Int로 전부 바꿔주었습니다.</br>
   - 로그아웃시 홈 화면으로 돌아가게 해주었습니다.</br>
   - 전반적인 설정쪽 layout 및 기능 구현 완료해주었습니다.</br>
   - 로그인이 되지 않은 상태에서 recordbutton을 눌렀을 때 로그인 후 delay(800)으로 기록하기 뷰를 띄워주는거를 delay(1000)으로 바꿔주었습니다.</br>
      - ![Simulator Screen Recording - iPhone 13 Pro Max - 2022-05-24 at 14 18 01](https://user-images.githubusercontent.com/77050826/169973618-d48cc057-dc78-4607-b908-29fed4f91745.gif)
      - delay 800으로 했을시 제가 넣어준 appcore 액션을 조금 늦게 인식해 아주 가끔 이런 상황이 나오는걸 확인해서 1000으로 바꿔준 후 테스트 해보니 문제가 없어졌습니다.</br>

2022-05-25 02:19 UTC, GREENOVER requested changes
@MoSonLee 
고생하셨습니다! 전체적으로 잘해주셨고 기능에서도 문제는 없어보입니다!
디자인적이나 더 나은 코드가 있을것 같아 코멘트를 남겨봤습니다.
확인해보시면 좋을것 같아요🙏🏻

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/SettingView.swift
> +    .padding(.bottom, 24)
네비게이션의 좌우측 패딩은 필요없나요?
피그마상 디자인의 패딩과 달라보입니다🙋🏻

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        bodyText: "로그아웃을 해도 꿈일기와\n 저장한 해몽은 사라지지 않아요",
피그마상 꿈 일기로 띄어쓰기 되야할것 같습니다..!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
>        )
좌우 패딩이 없습니다.
이 부분도 네비게이션이 잘못 잡혀있는건지 아래 컨텐츠의 패딩이 잘못잡힌건지 확인 필요합니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +      .padding(.bottom, 24)
좌우 패딩이 없습니다.
피그마와 다릅니다.
이게 위에서 정보 부분과 유사하게 네비게이션바의 패딩문제인지 밑에 컨텐츠의 문제인지 파악이 필요합니다!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +    }
피그마 디자인과 좌측 패딩이 다릅니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +              .frame(height: 16)
필요한가요?
피그마의 디자인 여백과 다릅니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/DropoutService.swift
> +          statusCode: String(response.statusCode),
String으로 감쌀 필요 없을것 같아요.
차라리 에러팩토리의 String 구현들을 전부 Int 타입으로 변경하는게 맞을것 같습니다!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/ResponseDto/SignUpUserDto.swift
> +  public let userId: Int
userId는 String으로 올거에요ㅠ
지금 서버가 변경 후 배포하지 않아서 그런것이고 response로 오는 모든 ID 형식의 타입들을 전부 String으로 받기로 노션에 기재되어 있습니다!
또한 제가 만들때 신경을 못쓴 부분인데 userID로 고유한 워딩인 id는 카멜 케이스를 따르지 않고 대문자로 통일해주시면 감사하겠습니다!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +          statusCode: String(response.statusCode),
전부 에러팩토리에서 statusCode의 타입을 Int로 변경하고 throw 해줄시에는 그냥 그대로 넘겨주는게 맞을것 같습니다!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoCore.swift
>        return .none
두 케이스의 순서가 변경되는게 다른 컨벤션들과 맞을것 같습니다🙋🏻

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +    )
디자인과 패딩이 상이해요.
네비게이션의 패딩이 안잡힌건가요 아니면 아래 VStack의 패딩이 잘못잡힌건가요?
확인이 필요해보입니다!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +        .padding(.bottom, 15)
`.padding(.vertical, 15)`로 동시에 패딩을 줄 수 있을것 같습니다.
코드 수가 주는 효과가 있습니다.
아래에도 동일하게 적용될 수 있겠네요!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +private struct makersWelcomeView: View {
Struct의 네이밍은 대문자로 시작합니다🙋🏻

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +      Button(action:{openURL(URL(string: "https://github.com/MoSonLee")!)}) {
버튼 뷰가 모두 중복됩니다.
하나의 뷰를 독립적으로 컴포넌트화 시켜 만들고 이를 반복을 통해 사용하는게 맞다고 보입니다.
즉 해당 State에서 딕셔너리로 이름과 URL주소 및 이모지들을 가지고 파라미터로 넘겨줘서 컴포넌트화 시킨 뷰를 불러야될것 같습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +      Button(action:{openURL(URL(string: "https://github.com/MoSonLee")!)}) {
액션을 뷰에서 해주면 안될것 같습니다.
Core 단의 액션으로 관심사를 옮기는게 맞아보입니다🙋🏻

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +  @Environment(\.openURL) var openURL
Core단으로 액션을 옮겨 사용하면 불필요한 변수가 될것 같습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +private struct MakersCardView: View {
CardView보다는 CardListView가 적절할것 같습니다.
단독적인 카드 하나만 있는것이 아닌 카드들이 모인 리스트의 형식이니까요.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  alertDoubleButtonReducer
withdrawAlertModal 빼고 logoutAlertModal만 pullback 받아도 괜찮은가요?

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    witdrawAlertModal: AlertDoubleButtonState? = nil
오탈자가 있습니다.
witdraw -> withdraw

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        primaryButtonHierachy: .warning)
끝 ) 한줄 띄우면 좋을것 같아요..!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        primaryButtonHierachy: .warning)
끝 ) 한줄 띄우면 좋을것 같아요..!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    case .withdrawButtonTapped:
enum에서 케이스의 선언은 logout이 먼저인데 여기서는 withdraw가 먼저나와 헷갈립니다.
enum의 케이스 선언 순서와 맞춰주시면 좋을것 같아요!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      return .none
액션이 무거워지는데 별도 메서드로 빼보면 어떨까요?
액션이 무거워질 수록 성능의 저하가 생깁니다ㅠ

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      profile?.popToRootViewController(animated: true)
동일하게 별도 메서드로 구분지어주면 좋을것 같습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +            return .noop
회원탈퇴 실패 시에는 토스트 메시지를 띄워줘야되지 않을까해요.
한번 디자인팀하고 얘기를 해보면 어떨까요?
실패했다는 메시지가 없다면 정상적으로 홈으로 빠져나가니 탈퇴된줄알고 유저는 사용을 안하거나 할 수 있는데
실제로 실패했기에 유저의 DB값은 아직 계속 서버에 남아있음으로 유저 입장에서는 오해 및 문제의 소지가 있습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        })
전체적인 흐름이 우선 탈퇴 버튼 클릭 시 
userID를 가지고 탈퇴 시켜주고 위 홈화면으로 이동시켜주는 로직이 그 다음 액션으로 나오면 어떨까해요.
즉 위 window를 이동시켜주는것을 하나의 private 메서드로 분리하고 return env.drop~~~에서 result가 success 즉 회원탈퇴 성공 시 해당 화면 이동 액션을 시켜줘야 맞다고 보입니다.
회원탈퇴 실패 시에는 토스트 메시지를 띄우고 화면 이동이 없어야지 유저가 인지할 수 있을것 같아요.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      return .none
현재는 Toast 사용하는 부분이 없는데 케이스로 정의되있는것 같아요.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  }
추후 쓰임이 없다면 제거되어도 되겠네요..!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  UserApi.shared.logout {(error) in
해당 UserApi는 카카오에 해당하는것인데 애플 로그인 관련된쪽에서 어떻게 사용되나요?

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  UserDefaults.standard.removeObject(forKey: "appleName")
이 메서드에서는 `UserDefaults.standard.removeObject(forKey: "isKakao")`는 필요없나요?

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +          .padding(.top, 15)
`.padding(.vertical, 15)`로 간소화 시키면 좋을것 같습니다.
아래들도 마찬가지일것 같아요!

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +      VStack(alignment: .leading, spacing: 0){
){ 한칸 띄워주세요.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +    VStack(spacing: 0){
){ 한칸 띄워주세요.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +
불필요한 개행이 있습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +    Button(action: {ViewStore(store).send(.withdrawButtonTapped)}) {
{} 안에 액션 구현 사이들의 공백(띄어쓰기)을 하나씩 만들어주면 좋을것 같습니다.

2022-05-25 02:19 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/SettingView.swift
> +              .padding(.top, 15)
`.padding(.vertical, 15)`로 간소화 해주면 좋겠습니다!

2022-05-25 06:28 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        bodyText: "로그아웃을 해도 꿈일기와\n 저장한 해몽은 사라지지 않아요",
해결해주었습니다..!

2022-05-25 06:30 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoCore.swift
>        return .none
해결해주었습니다..!

2022-05-25 06:32 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +        .padding(.bottom, 15)
해결해주었습니다.!

2022-05-25 06:32 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +private struct makersWelcomeView: View {
넵! 고쳐주었습니다.!

2022-05-25 06:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    witdrawAlertModal: AlertDoubleButtonState? = nil
해결해주었습니다.!

2022-05-25 06:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  alertDoubleButtonReducer
해결해주었습니다.!

2022-05-25 06:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        primaryButtonHierachy: .warning)
수정해주었습니다!

2022-05-25 06:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        primaryButtonHierachy: .warning)
수정해주었습니다!

2022-05-25 06:42 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    case .withdrawButtonTapped:
수정해주었습니다!

2022-05-25 06:45 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      return .none
앗 당연히 그렇겠네요..! 별도로 빼주니 코드도 확실히 줄어들고 가독성도 좋아지네요..! 수정해주었습니다!

2022-05-25 06:52 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  }
넵 제거해주었습니다!

2022-05-25 06:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  UserApi.shared.logout {(error) in
앗 그러네요 삭제해주었습니다..!

2022-05-25 06:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  UserDefaults.standard.removeObject(forKey: "appleName")
앗 그렇겠네요..! 넣어주었습니다.!

2022-05-25 06:54 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +          .padding(.top, 15)
수정해주었습니다!

2022-05-25 06:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +      VStack(alignment: .leading, spacing: 0){
수정해주었습니다!

2022-05-25 06:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +    VStack(spacing: 0){
수정해주었습니다!

2022-05-25 06:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +
수정해주었습니다!

2022-05-25 06:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +    Button(action: {ViewStore(store).send(.withdrawButtonTapped)}) {
수정해주었습니다!

2022-05-25 06:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/SettingView.swift
> +              .padding(.top, 15)
수정해주었습니다..!!

2022-05-25 06:59 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/SettingView.swift
> +    .padding(.bottom, 24)
앗 그렇네요 수정해주었습니다..!

2022-05-25 07:07 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
>        )
수정해주었습니다!

2022-05-25 07:07 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +      .padding(.bottom, 24)
수정해주었습니다.!

2022-05-25 07:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +    )
수정해주었습니다!

2022-05-25 07:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +private struct MakersCardView: View {
수정해주었습니다!

2022-05-25 07:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +            return .noop
저도 좀 의아해서 서버팀에 여쭤봤었는데 다시 이유와 같이 한번 말씀드려보겠습니다.!

2022-05-25 07:20 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      profile?.popToRootViewController(animated: true)
수정해주었습니다!

2022-05-25 07:24 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +            return .noop
음 서버팀에 여쭤볼 사항인건가요~?

2022-05-25 07:29 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +              .frame(height: 16)
삭제해주었습니다!

2022-05-25 07:30 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/ResponseDto/SignUpUserDto.swift
> +  public let userId: Int
아 그렇네요 String으로 변경해주었습니다!

2022-05-25 07:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +          statusCode: String(response.statusCode),
수정해주었습니다!

2022-05-25 07:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/DropoutService.swift
> +          statusCode: String(response.statusCode),
수정해주었습니다!

2022-05-25 08:59 UTC, MoSonLee commented
우선 MakersView 관련된 뷰쪽은 안 봐주셔도 될거 같습니다..!! ( 회원가입, 실패 관련 logic은 좀 크리티컬 해보여서 먼저 pr 올려봤습니다..!)

Postman으로 확인해봤을때 아직까지 int로 오는 것 같아 회원가입이 제대로 되는 것 같지는 않습니다.!
![image](https://user-images.githubusercontent.com/77050826/170223715-79974799-c7f9-412e-b3d5-46e36423c44a.png)
![Simulator Screen Recording - iPhone 13 - 2022-05-25 at 17 51 21](https://user-images.githubusercontent.com/77050826/170223643-25f764ef-acad-474f-8c8a-9659b41ebdcd.gif)

우선 기능적으로 회원탈퇴 실패시 -> presnettoast 메세지(아직 디자인팀에게 답이 오지않아 임의로 넣어뒀습니다.)
성공시 -> home으로 이동 시켜두었습니다..!

makers까지 마무리 짓고 올릴려하다가.. 회원 가입, 탈퇴쪽은 좀 중요해보여서 먼저  pr 올려봤습니다..! ( 제가 잘못 작성한 것인지 서버측 문제인지 잘 확인이 안 되어서요..! ㅜㅜ)

makers 쪽은 아예 안 봐주셔도 될것 같습니다..! 아예 전체적으로 refactoring 중이라서요..! 🙏

2022-05-25 09:18 UTC, GREENOVER requested changes
좋습니다!
승후님 이번 PR에서부터 단기간에 코드의 질이라던지 짜임새라던지 하는 부분에서 모두 급성장 하신게 코드로 보여지네요!👍👍👍
슬랙에 답변드린 바와 같이 Makers쪽까지 리팩토링 된 후 최종 리뷰 및 테스트 해보겠습니다!

2022-05-25 11:25 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +        })
수정했습니다..!

2022-05-25 15:58 UTC, MoSonLee commented
리뷰해주신 내용들 토대로 전반적으로 바꿔주었습니다.! 🙏🙏
makersView, core refactor 완료해주었습니다.

### Issues 
회원조회, 가입, 탈퇴 모두 현재 안 되는 상태입니다..!
코드는 크게 달라진것이 없어 생각되기론 userId -> userID 로 수정해줘서 서버측에서 주는 이름과 달라서 그런 것 같습니다..!
그러면 코드에 문제가 없으면 서버측에 다른 네이밍으로 요청하는게 맞는걸까요.?!
혹시 제 코드적 문제면 코드를 수정해보겠습니다..!

2022-05-26 00:35 UTC, GREENOVER reviewed
Makers 부분 아주 잘 분리 및 재사용 해주셨네요👍
몇가지 코멘트 조금 더 달았습니다🙏🏻

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
>    public let secondImage: Image
디자인 기획 상에서는 추후 애플 이모지를 넣는다고 되있는것 같은데 
그렇다면 애플 이모지는 String 타입일텐데 추후 Image로 변환되는 String extension 메서드가 필요해보입니다!

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
>    public func hash(into hasher: inout Hasher) {
한줄 개행 하면 좋을것 같아요!

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DropoutRequestDto.swift
> +    case userID
서버에서는 userId 일테니 코딩키 처리가 있어야합니다.
`userID = "userId"`

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/SaveDreamRequestDto.swift
> +    case userID = "userID"
userId가 되야합니다.
서버에서는 userId로 넘겨주는것이고 우린 그걸 받아서 userID로 쓰겠다는 뜻입니다.

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/UserDreamListRequestDto.swift
> +    case userID = "userID"
userId가 되야합니다.
서버에서는 userId로 넘겨주는것이고 우린 그걸 받아서 userID로 쓰겠다는 뜻입니다.

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/ResponseDto/CheckUserDto.swift
> +    case checkValue, userID
서버에서는 userId 일테니 코딩키 처리가 있어야합니다.
`userID = "userId"`

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +      VStack(alignment: .leading, spacing: 0) {
로그아웃/탈퇴하기 버튼 뷰들과 위 이름/계정의 좌측 패딩이 피그마와 다릅니다.

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
VStack으로 감싸주신 이유가 있나요?

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
VStack으로 감싸주신 이유가 있나요?

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
VStack으로 감싸주신 이유가 있나요?

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack {
VStack으로 감싸주신 이유가 있나요?

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +  var makersURL: URL
private해도 괜찮을것 같네요..!

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +    secondImage: Image = R.CustomImage.homeActiveIcon.image
Makers Stub에 이미지의 값들이 들어가 있는것 같은데 이미지들만 기본값 설정을 해주신 이유가 있나요?

2022-05-26 00:35 UTC, GREENOVER commented on Mongsil/Mongsil/Application/AppCore.swift
> +      }
여기서 직접 사용하면 안될것 같아요.
하위 코어에서 presentToast 액션을 발행하도록 해놨습니다.
거기서 발행 후 여기서는 위에 나온 사용처럼 풀백만 받아 매칭만 시켜주면됩니다.
이유는 이렇게 되면 모든것을 AppCore에서 토스트 메시지 관리를 해줘야 맞는 그림인데 그렇게 되면 각각의 하위뷰에서 어떨때 어떤 토스트 메시지를 띄워야하는지 AppCore를 봐야지만 알 수 있는 로직입니다.

2022-05-26 01:33 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
>    public func hash(into hasher: inout Hasher) {
수정해주었습니다!

2022-05-26 01:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DropoutRequestDto.swift
> +    case userID
수정해주었습니다!

2022-05-26 01:35 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/SaveDreamRequestDto.swift
> +    case userID = "userID"
수정해주었습니다!

2022-05-26 01:36 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/UserDreamListRequestDto.swift
> +    case userID = "userID"
수정해주었습니다!!

2022-05-26 01:37 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/ResponseDto/CheckUserDto.swift
> +    case checkValue, userID
수정해주었습니다!

2022-05-26 01:40 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
삭제해주었습니다!

2022-05-26 01:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
삭제해주었습니다!

2022-05-26 01:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack(alignment: .leading) {
삭제해주었습니다!

2022-05-26 01:41 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/AppInfoView.swift
> +          VStack {
삭제해주었습니다!

2022-05-26 01:43 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +  var makersURL: URL
넵! 수정해주었습니다!

2022-05-26 01:44 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/AppInfo/Makers/MakersView.swift
> +    secondImage: Image = R.CustomImage.homeActiveIcon.image
삭제해주었습니다!

2022-05-26 02:12 UTC, MoSonLee commented on Mongsil/Mongsil/Application/AppCore.swift
> +      }
넵 수정해주었습니다!

2022-05-26 02:15 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
>    public let secondImage: Image
추가해주었습니다!

2022-05-26 02:26 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +      VStack(alignment: .leading, spacing: 0) {
UserName , Email측은 28로 동일한것 같은데 혹시 뭐가 틀렸을까요..? 
밑에 로그아웃/ 탈퇴하기는 수정해주었습니다!

2022-05-26 02:31 UTC, MoSonLee commented
### 수정완료했습니다..!
   - userId를 멍청하게 다 userID로 바꿨었네요..ㅜㅜ 
   -  수정해주었습니다! 회원조회 가입 탈퇴 로그아웃 문제 없는 것 같습니다.!
   - 필요없는 VStack들 모두 지워줬습니다!
   - layout 수정해주었습니다.!

2022-05-26 03:06 UTC, GREENOVER requested changes
불필요하게 변경되거나한 부분 코멘트 드렸습니다.
그 다음 기능에 이슈가 있습니다.
보관함에서 설정을 간다음 탈퇴 시 아직 보관함에 매칭되어 있습니다.
홈 탭으로 이동시켜주어야 할것 같습니다.

https://user-images.githubusercontent.com/72292617/170407589-dd524407-4e2e-49d3-b4c3-3eeda7e8e736.mp4

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Application/AppCore.swift
> +        return .none
Toast 이펙트 발행이 있어야하지 않을까요?
Profile에서 토스트 메시지를 통해 toastState를 만들어주는것은 거기서의 관심사이고
이를 띄워주는것은 앱 코어에서 해줘야될것 같아요.

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  public var secondImageToString: String?
Image와 String둘다 있고 Image에 대한 처리가 없는데
자 그럼 생각해볼때,
해당 Maker의 첫번째 애플 이모지로 "🍏" 를 주었다고 쳐볼께요.
그렇다면 어떻게 Makers에서 활용하게 될까요?

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +            UserDefaults.standard.set(userID, forKey: "userId")
UserDefaults에서 userId 값을 바꿔주신 이유가 있나요?

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +          UserDefaults.standard.set(response.userID, forKey: "userId")
UserDefaults에서 userId 값을 바꿔주신 이유가 있나요?
어딘가에서는 userID로 쓰고 있을거같아요.

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      let userID =  UserDefaults.standard.string(forKey: "userId") ?? ""
여기도 userId로 바뀐 이유가 있나요?

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +
이러한 공백들이 추가 되었는데 Lint가 적용안된것 같아요!
불필요한 변경 사항은 없애면 좋을것 같습니다🙋🏻

2022-05-26 03:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +      VStack(alignment: .leading, spacing: 0) {
밑에 로그아웃/탈퇴하기 버튼 뷰의 수정을 말씀드리면서 여길 비교했던것 같습니다!

2022-05-26 03:55 UTC, GREENOVER commented
추가적으로 현재 userID에 대해 서버에서 check한 후 해당 값을 UserDefault에 값으로 저장하고 이를 사용하고 있는데,
그러지 않고 SharedState에서 프로퍼티를 생성해 값을 넣어줘서 이를 전역적으로 사용하면 어떨까요?
UserDefault는 앱이 종료되더라도 디바이스에 캐시로 남아있게 하는 값들에 대해서 사용했던것이고
userID는 관심사가 다르다고 생각이 들어서요.
다이어리 및 꿈일기등에 대해 불러오거나 저장하거나 할때도 userID를 사용해야하는데 현재 구조라면 매번 해당 로직에서 UserDefault값의 코드를 가져와야되며 관리가 힘들고 헷갈릴것 같아요.
state.shared.userID로 state에서 이 userID 값을 가지고 사용하는게 조금 더 편리하고 관심사에도 맞다고 생각듭니다.
즉 앱이 켜질때 checkUser API를 쏘고 이 값을 sharedState에서 프로퍼티에 저장하는것이 맞지 않을까해요🙋🏻

2022-05-26 04:03 UTC, MoSonLee commented on Mongsil/Mongsil/Application/AppCore.swift
> +        return .none
다시 추가해주었습니다!

2022-05-26 04:03 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  public var secondImageToString: String?
수정해주었습니다!

2022-05-26 04:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +            UserDefaults.standard.set(userID, forKey: "userId")
수정해주었습니다!

2022-05-26 04:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +          UserDefaults.standard.set(response.userID, forKey: "userId")
수정해주었습니다!

2022-05-26 04:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +      let userID =  UserDefaults.standard.string(forKey: "userId") ?? ""
다시 수정해주었습니다!

2022-05-26 04:04 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileView.swift
> +
넵 수정하겠습니다!!

2022-05-26 04:23 UTC, MoSonLee commented
앗 추가 코멘트를 확인을 못하고 푸쉬해버렸네요! ㅜㅜ
일단 위에 코멘트 주신 부분들은 다 수정했습니다..!
스위프트린트가 지금 왠지는 모르겠는데 버전이 다르다고 설치가  안 되네요ㅜㅜ 좀 더 찾아봐서 설치해보겠습니다!1


추가 코멘트는 이제 확인했습니다!
어떻게 해야할지 감은 오는데 좀 헷갈리는 부분들이 많네요..! ㅜㅜ
지금 바로 작업하기에 머리가 너무 안 돌아가서 나중에 다시 확인해봐도 괜찮을까요..?!( 혹시 머지가 급한 상황인가 해서요..!)

2022-05-26 05:40 UTC, GREENOVER commented
@MoSonLee 
아뇨 당장 오늘 처리해야할 사항은 아니니 토요일전까지 최대한 해보시면 좋을것 같습니다!

2022-05-26 05:54 UTC, MoSonLee commented
넵! 해보겠습니다!!
근데 궁금한게 있는데 앱이 켜질떄(appdelegate)시에 checkUSer를하게 되면 맨 처음 앱을 설치한 유저들에겐
 로그인이 안 된 상태가 default일 테니 회원조회가 되지 않는 다는 토스트가 먼저 홈에서 뜨게 될텐데 그건 상관 없는걸까요?
 회원조회가 되지 않는다는 팝업 -> 회원가입 순으로 진행되어도 문제가 없는걸까 싶어서요!

2022-05-26 06:19 UTC, GREENOVER commented
@MoSonLee 
회원 조회가 되지 않았다는 토스트 메시지는 제가 임의로 넣은것으로 기억합니다.
불필요한 토스트 메시지라면 빼도 될것 같긴한데 그에 앞서
제 코멘트가 적절치 못했네요..!
말씀하신바와 같이 앱이 켜질때는 필요 없을것 같고 checkUser를 하는 시점에서 SharedState의 변수 값으로 데이터만 넣어주면 될것 같아요.
핵심은 유저 디폴트 사용보다는 SharedState 사용입니다!

2022-05-26 06:40 UTC, MoSonLee commented
넵 이해했습니다!구현해보겠습니다!

2022-05-27 10:34 UTC, MoSonLee commented
checkUser할때 userDefaults -> shareState에서 변수를 선언해서 변경해주었습니다..!
sharedState가 조금 익숙치가 않아서 빼먹은 부분이나 그런게 있으면 빠르게 고쳐보겠습니다..!
감사합니다!

2022-05-29 02:39 UTC, GREENOVER requested changes
수정된것 확인 후 재 코멘트 드렸습니다!
훨씬 많이 잘 수정되었네요👍
마무리로 다듬어 보시면 좋을것 같아요.
또한 현재 구성원들의 애플 이모지 및 링크를 최종적으로 같이 심어 최종 코드 수정 후 리뷰 재요청을 해주시면 감사하겠습니다!
아마 애플 이모지를 String으로 넣게되었을때 이미지로 변환하는 로직에서 발생하는 문제가 있을거에요.
이 부분 코멘트 드렸습니다!

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				LastUpgradeCheck = 1340;
해당 값들이 바뀐 이유가 있을까요?

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
해당 값이 추가된 이유가 무엇인가요?
혹시 SwiftLint를 팟으로 추가해보거나 설치하려다 들어간 것이면 제거하는것이 나아보입니다.
저희는 라이브러리 의존성 관리도구로 SPM을 사용하기로 했기에 Lint 라이브러리는 현재 홈브루로 설치했습니다.
이에 Lint 사용을 하고싶으시면 홈브루로 설치해야됩니다..!

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/xcshareddata/xcschemes/Mongsil.xcscheme
> +   LastUpgradeVersion = "1340"
해당 값도 변경하신 이유가 있나요?

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Application/AppCore.swift
> +
이러한 Lint 룰이 적용되지 않아 발생한 공백들은 제거하는것이 나을것 같습니다.
이후 나오는 이러한 부분들 모두 공통 코멘트입니다..!

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    secondImageToString: String? = nil,
순서가 상이합니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    self.makersURL = makersURL
실제로 이니셜라이저에서 인자로 받고 사용되지 않는것이 있는데 이유가 있으신가요?

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Application/AppCore.swift
> +        popToRoot()
필요한가요?
아래 코드로만 충분하지 않은가 싶어서요.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
아마 해보시면 아시겠지만 🙋🏻와 같은 애플 이모지를 String으로 넣었을때 제대로 작동 안할거에요.
이 부분 수정이 필요합니다!
또한 해당 코드가 유의미한 메서드인지 모르겠습니다.
단순히 Image에 값을 넣어주는것인데  17번 라인과 같은 구문에서 `Image(systemName: firstImageToString)`으로 충분히 표현될것 같은데 메서드로 만들어주신 이유를 모르겠습니다🙋🏻

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +import Foundation
불필요할것 같습니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    secondImage: R.CustomImage.homeDisabledIcon.image,
이제 더이상 불필요한 두 코드일것 같습니다.
mock 데이터로 넘겨줄때 String으로 넘겨주고 Image 프로퍼티는 연산 프로퍼티이니 값을 직접 주입해주면 안됩니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +          statusCode: String(response.statusCode),
String으로 감쌀 이유가 없습니다.
Int 타입으로 변경시켜줘야될것 같아요.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
키값이 userID로 고유한 ID, URL등과 같은것은 특수하게 카멜케이스에서 벗어나는 컨벤션이면 좋겠습니다.
제가 기존에 해당 에러팩토리 키값들을 막 만들었기에 네이밍에서 수정할 부분들이 있을거에요.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
>          "DreamID": DreamID,
"dreamID"로 수정되면 좋을것 같아요. 대문자로 시작된 오탈자입니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
>      DreamID: String,
d 소문자로 시작되어야합니다.
기존 오탈자입니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
여기서 "userID"로 키값 변경이 되어야 맞을것 같습니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserService.swift
> +    print(email)
이제 제거되어도 될 코드 같습니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/SharedState/SharedState.swift
> +  public var userId: String?
userID로 컨벤션을 맞추는게 좋아보입니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +  case setUserId(String)
해당 액션이 불리는 액션 다음에 정의되고 구현되는게 순서 흐름에 맞아 보입니다!

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +  case setUserId(String)
`setUserID`로 네이밍 컨벤션을 따르면 좋을것 같습니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  case setUserIdNil
해당 케이스의 위치 조정이 필요해보입니다.
실제로 사용되는 부분 즉 회원탈퇴인 withdrawButtonTapped 다음 일어나는 액션이니 바로 다음으로 위치하는것이 맞지 않을까해요.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    case .setUserIdNil:
해당 액션이 추후 재사용성 있게 사용되려면
setUserID로 액션을 정의하고 인자로 String?을 받으면 어떨까요?
그리고 호출하는쪽에서 nil값이던 문자열이던지 넘겨주면 사용성이 증가할것 같습니다.

2022-05-29 02:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +public func popToRoot() {
해당 메서드를 외부에서도 쓰인다면 메서드 구현 위치가 ProfileCore가 아닌 다른 별도의 Extension 파일을 만들거나 해서 그쪽으로 관심사를 옮겨야할것 같고 그게 아니고 여기서만 쓰인다면 private해도 될것 같습니다!
그런데 제 생각엔 현재 여기서만 쓰더라도 이러한 공통된 메서드 로직은 추후 사용될 여지가 다분함으로 별도로 UIViewController+extensions이란  파일을 만들어 그쪽에서 구현해놓으면 좋지 않을까해요.

2022-05-29 03:54 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +import Foundation
수정해주었습니다!

2022-05-29 03:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
수정해주었습니다!!

2022-05-29 03:55 UTC, MoSonLee commented on Mongsil/Mongsil/Application/AppCore.swift
> +        popToRoot()
수정해주었습니다!

2022-05-29 03:57 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +          statusCode: String(response.statusCode),
수정해주었습니다!

2022-05-29 03:58 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
>          "DreamID": DreamID,
수정해주었습니다!

2022-05-29 03:58 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
수정해주었습니다

2022-05-29 03:59 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserService.swift
> +    print(email)
수정해주었습니다

2022-05-29 04:00 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/SharedState/SharedState.swift
> +  public var userId: String?
수정해주었습니다

2022-05-29 04:02 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Login/LoginCore.swift
> +  case setUserId(String)
넵! 수정해주었습니다

2022-05-29 04:03 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +  case setUserIdNil
수정해주었습니다!

2022-05-29 04:07 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +    case .setUserIdNil:
넵 이해했습니다! 수정해주었습니다

2022-05-29 04:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Setting/Profile/ProfileCore.swift
> +public func popToRoot() {
넵 새로운 파일 만들어 거기에 넣어줬습니다!

2022-05-29 04:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
>      DreamID: String,
수정해주었습니다

2022-05-29 04:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
"id": userID 로 수정해주었습니다

2022-05-29 04:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    secondImageToString: String? = nil,
수정해주었습니다

2022-05-29 04:21 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    self.makersURL = makersURL
앗 그러네요 ㅜㅜ 추가해주었습니다!

2022-05-29 04:27 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				LastUpgradeCheck = 1340;
제가 직접 변경해준 사항이 아니라 어떻게 추적을 해야할지를 모르겠습니다..! ㅜㅜ

2022-05-29 04:27 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
swiftlint는 홈브루로만 설치했습니다..! 
저 파일도 어떻게 추적을 해야할지를 모르겠습니다..! ㅜㅜ

2022-05-29 04:27 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/xcshareddata/xcschemes/Mongsil.xcscheme
> +   LastUpgradeVersion = "1340"
이것도 제가 직접 변경해준 사항이 아니라 어떻게 추적을 해야할지를 모르겠습니다..! ㅜㅜ

2022-05-29 04:28 UTC, MoSonLee commented on Mongsil/Mongsil/Application/AppCore.swift
> +
넵!

2022-05-29 04:36 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				LastUpgradeCheck = 1340;
![스크린샷 2022-05-29 오후 1 35 39](https://user-images.githubusercontent.com/72292617/170852421-ef265f5a-2e56-4eda-b4c7-29888de51ab5.png)
해당 캡쳐화면 참고하시면 좋을것 같아요.
패키지에 담긴 프로젝트 파일을 접근해서 수정해주시면 될것 같습니다.

2022-05-29 04:36 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
위의 코멘트와 동일합니다.

2022-05-29 04:37 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
id로만으로는 어떤 아이디인지 유저의 dreamID인지 userID인지 에러 메시지만으로 판단하기 힘들 수 있습니다.
userID는 어떠신가요?

2022-05-29 04:43 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				LastUpgradeCheck = 1340;
정말 감사합니다..! 열어서 모두 수정해주었습니다!

2022-05-29 04:43 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
수정해주었습니다!

2022-05-29 04:43 UTC, MoSonLee commented on Mongsil/Mongsil.xcodeproj/xcshareddata/xcschemes/Mongsil.xcscheme
> +   LastUpgradeVersion = "1340"
이것도 마찬가지로 수정해주었습니다!

2022-05-29 04:45 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/UserDreamListService.swift
> +        "userId": userID,
"userID": userID 
넵..! 이렇게 다시 수정해주었습니다..!

2022-05-29 06:52 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
찬우님 제가 이걸 작업하다가 알게 된건데..!
애플 이모지는 systemName으로 인식하지 않고 애초에 이렇게 이미지가 아닌 text에 유니코드를 넣어줘서 이미지를 text로 보여주는 것 같아서요..!
애플 이모지(애초에 String) -> Image 가 아닌
애플 이모지(String) -> 유니코드를 넣어줘서 그림처럼 보이게한 String 값으로 보여지는데 혹시 제가 잘못 생각한걸까요?
그레서 이모지를 보여줄라면 Text에 저렇게 넣어야되더라구요..!
![image](https://user-images.githubusercontent.com/77050826/170855991-f8be4ca1-407a-4be6-9c7c-53f458dd134e.png)


![image](https://user-images.githubusercontent.com/77050826/170855869-8dacec80-eb21-43d8-9027-52ace168d042.png)
![image](https://user-images.githubusercontent.com/77050826/170855974-ac19c52f-b224-46f5-8c2c-60367c01f4c3.png)

2022-05-29 08:37 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
말씀하신 방법도 방법이지만 제가 알기론 애플 이모지를 스트링으로 받아 이미지로 변환 해주는 메서드가 애플에서 제공되는걸로 알고 있는데 아닐까요?

2022-05-29 08:39 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
아 아마 기본 제공되는 기능들로 해당 기능을 구현해줄수 있을것 같아요! m

2022-05-29 08:41 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
물론 승후님이 말씀하신 방법은 더 편하긴 합니다! 다만 직관적인지는 잘 모르겠어서요.
이게 코드만 봤을때 어떤 이미지인지 알 수 있을까란 의문이 들어서요ㅠ

2022-05-29 10:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
제가 한번 찾아보고 고민해봤는데
 이모지를 uiimage로 변경해주는 method가 uikit에선 있는데 swiftui에서는 제가 못 찾는거 일 수도 있는데 안 보입니다..! ㅜㅜ
 제공되는 기능들로 어떻게 구현해야 가능할까요..?
 
 예를들어 🍏 이모지는 String 값인데 이걸 변환시켜도 저것의 유니코드가 나올 것 같아서요..!
 저 이모지를 Image값으로 바꾸어주거나 Image가 인식해줄 수 있는 systemname으로 변환을 어떻게 시킬 수 있을까요..?! ㅜㅜ

2022-05-30 01:06 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
말씀하신바와 같이 UIImage로 우선 변환을 해주는 코드를 String Extension해서 구현해준 후 
변경된 UIImage를 가지고 SwiftUI에서의 Image 뷰 타입으로 변경해주면 됩니다.
`Image(uiImage: xxx)`
여기서 중요한것은 유니코드를 사용하지 않는것에서의 이점이라고 생각해요.
유니코드만 보고 저게 어떤 값을 내포하는지 코드만으론 알 수 없고 직접 찾아서 어떤 이미지를 들고 있는지 확인해야 합니다.
즉 추가 수정 시 코드에서만 쉽게 애플 이모지를 넣어 이뤄지는게 아닌 해당 이모지의 유니코드를 찾아야함에 한단계 더 불편함이 있습니다.
즉 아래와 같이 쓰일 수 있는게 가장 베스트입니다.
![스크린샷 2022-05-30 오전 10 05 38](https://user-images.githubusercontent.com/72292617/170899920-551d20cc-4666-47f2-87b3-69e19c6a5562.png)
위와 같이 이모지를 문자열로주고 말씀드린 UIImage 변환 후 Image 변환까지 거쳐준다면
![Simulator Screen Shot - iPhone 11 - 2022-05-30 at 10 03 06](https://user-images.githubusercontent.com/72292617/170899947-5445285e-7bfa-4c79-b17c-a0619a5cf207.png)
이렇게 원하는 결과물이 나올것 같습니다.
(크기는 임의로 해줬기에 신경 안쓰셔도 됩니다.)

2022-05-30 01:10 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +    secondImageToString: String? = nil,
실제로 firstImageStr로 변수를 사용하는데 여기서 인자 값으로 firstImageToString을 사용해 헷갈립니다.
통일 되면 어떨까요?
또한 더이상 first/secondImage를 인자로 주입 받을 필요는 없습니다.
추가로 first/secondImageToString이 옵셔널일 필요는 없을것 같아요.
옵셔널이라면 위 first/secondImageStr도 동일하게 맞춰줘야할것 같고 위에서 해당 값들의 기본값을 줄 필요도 없을것 같아요.
first/secondImageToStr로 값을 이니셜라이저를 통해 사용할거라면 var로 바뀌어야 될것같구요.
요러한 부분들이 다른 쪽에서도 있는지 확인해보시면 좋을것 같습니다!

2022-05-30 04:31 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Makers.swift
> +  }
수정해주었습니다..!

2022-05-30 04:59 UTC, GREENOVER requested changes
@MoSonLee 
리팩토링 고생하셨습니다!
마지막 코멘트들만 수정되면 될것 같습니다🙋🏻

2022-05-30 04:59 UTC, GREENOVER commented on Mongsil/Mongsil.xcodeproj/project.pbxproj
> +				CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
해당 값 다시 추가되었습니다.

2022-05-30 04:59 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/View/UIViewController+extensions.swift
> +}
실제 구현을 보면 UINavigationController가 해주는 역할 같습니다.
고로 이미 기존에 만들어진 UINavigationController+extensions 파일로 구현을 위치 시키면 어떨까요?

2022-05-30 04:59 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/View/View+extensions.swift
> +extension String {
실제 String의 extension인데 파일명은 View의 익스텐션으로 보여집니다.
별도 파일로 분리해야되지 않을까요?

2022-05-30 04:59 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/View/View+extensions.swift
> +  func textToImage() -> UIImage? {
추후 모듈 분리 후 사용을 위해선 public해야되지 않을까 싶습니다.

2022-05-30 06:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/View/UIViewController+extensions.swift
> +}
이동시켜주었습니다..!

2022-05-30 06:24 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/View/View+extensions.swift
> +extension String {
수정했습니다!

2022-05-30 06:28 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/View/View+extensions.swift
> +  func textToImage() -> UIImage? {
수정해주었습니다!

2022-05-30 06:30 UTC, MoSonLee commented
모두 수정 후 pr 올려주었습니다..!

2022-05-30 06:45 UTC, GREENOVER requested changes
고생하셨습니다!
정말 마지막 마이너한 파일 위치 관련 리뷰 하나 남겼습니다!
해당 코멘트만 반영되면 어프로브하겠습니다🙏🏻

2022-05-30 06:45 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/View/String+extensions.swift
> +extension String {
요 파일은 기본 타입의 extension이라고 보여서 View 폴더 밖에 위치해야될것 같아요🙋🏻

2022-05-30 06:48 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/View/String+extensions.swift
> +extension String {
수정해주었습니다!

2022-05-30 06:48 UTC, MoSonLee commented
### 최종 수정 완료해주었습니다!

2022-05-30 06:49 UTC, GREENOVER approved these changes
고생 많으셨습니다!
머지 부탁드립니다🙏🏻

2022-05-30 06:49 UTC, merged