refactor: apply userCard api in core
depromeet/mongsil-iOS pull request #76
Opened 2022-06-10 16:40 UTC by MoSonLee

### Task
   - 유저 꿈 일기 API 코어 액션 단에서 연동</br>

### Description
   - api 로직 연결은 안 해봐서 제대로 한건지 잘 확신이 안 서네요..ㅜㅜ</br>
   - 일단 기록, 검색쪽 제외하고는 로직을 다 추가햐주었습니다!(Mark 해주신 부분에 완료 한 부분은 -> 완료라고 표시해봤습니다.)</br>
   - 제대로 한건지를 테스트가 불가능해서 혹시 잘못 구현했으면 바로 다시 구현해보겠습니다.!</br>

2022-06-11 00:36 UTC, GREENOVER commented
@MoSonLee 
테스트가 불가능한 이유가 있을까요?
일기 삭제 및 저장 등의 테스트는 목 데이터를 가지고 충분히 해볼 수 있지 않을까해요!
수정도 마찬가지일테고 실제 기록하기 부분의 구현이 없다 하더라도 목 데이터를 로직에서 넘겨주는 방식으로 해당 API가 정상적인지 잘 연동되었는지 등 테스트는 가능할거라 생각합니다🙋🏻
이에 코드 리뷰에 앞서 요 부분부터 반영하여 진행해주시면 감사하겠습니다.
해당 코드만으로는 저도 마찬가지로 테스트가 불가하기에 정상적인 리뷰가 되기 어려울것 같습니다.

2022-06-11 04:52 UTC, MoSonLee commented
아 이해했습니다.!
목 데이터를 추가해서 하나씩  테스트를 하며 잘못 된 점은 수정하고 다시 pr올려보겠습니다!!

2022-06-11 05:55 UTC, GREENOVER commented
네 좋습니다!
저희도 어떻게 테스트를 해보면 될지 테스트 코드 혹은 테스트 했던 방법도 PR에 추가해주시면 감사하겠습니다~

2022-06-13 07:58 UTC, MoSonLee commented
### Description
   - 현재 서버측에서 cardId를 string -> array로 바꿔주시지 않아서 test가 불가능한 상태입니다..!
   - 우선 기록하기, 검색하기 쪽 제외하곤 로직을 연결해주었습니다!
   - 최신상태 유지하기 위해 (찬우님이 작업해주신) 새로 메인에 머지된 파일을 pull 받아놨습니다!
   - 나중에 서버측에서 변경해주시면 테스트 코드까지 작업후에 재pr올려보겠습니다!
   - 테스트 코드가 없는 상태라 리뷰용이 아닌 최신 상태 유지를 위해 pr올려놓은 상태입니다..!

2022-06-13 08:02 UTC, GREENOVER commented
@MoSonLee 
넵 고생하셨습니다!
서버측 변경 반영되고 테스트 코드 작업이 되면 그때 리뷰하겠습니다🙌
혹시 내일 오전정도까지 서버 측 API 수정이 되지 않았다면 트래킹해서 저한테 알려주시거나 건웅님께 요청 부탁드립니다!

2022-06-14 04:48 UTC, MoSonLee commented
### Description
   - code convention 안 맞는 부분들 수정해주었습니다</br>
   - 기록 편집 부분으로 이동하는 것 제외하고는 로직들 전부 연결해주었습니다.</br>
   - 궁금한게 제가 testcode를 작성해본 적이 없어서요..!</br>
      - 현재 기록하기가 완료되지 않은 시점에서 cardId 값을 가진 diary를 어떻게 set하고 delete가 정상 작동하는지 테스트를 해봐야할지 잘 모르겠습니다.. 😭😭</br>

2022-06-14 04:54 UTC, GREENOVER commented
@MoSonLee 
기록하기가 완료되지 않았더라도 saveUserDream과 같은 저장을 할 수 있는 API는 이미 존재하기에 해당 API에 mock 데이터를 넣어 통신 시켜주면 되지 않을까합니다.
즉 뷰단에서 넘겨주는 데이터가 아니라 현재 모델에서 Stub으로 구현된 테스트 더미 데이터를 가지고 현재 로직에 연결된 API들을 호출해주거나 하면 될거라 생각이 들어요.
만약 그게 어렵다면 PostMan을 통해서 값을 넣어줘서 데이터를 생성해도 될것 같구요.
테스트 코드를 따로 메서드 및 파일을 만들어 작성하지 않아도 제 의도는 현재 승후님이 작업하신 PR에 대해 승후님 조차 테스트 데이터를 가지고 테스트 해보지 않았기에 이 로직들의 호출 및 기능이 정상적인지 확신할 수 없다고 생각합니다.
이를 해결해봐야할것 같아요🙋🏻
그게 완료되어야 정상적인 리뷰가 가능할것 같아요.

2022-06-15 17:27 UTC, MoSonLee commented
### Description
   - Postman으로 diary를 보내 정상적으로 List에 뜨는 것 확인했습니다.</br>
   - 확인해보니 storageview에서 date를 받아올 때 서버에서는 string으로 보내주고 있고 저희 xcode에서는 date를 사용하는것 같아 바로 뜨지는 않아서 확인해보기 위해 아래 사진처럼 바꿔서 실행해봤습니다.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/77050826/173886666-c79ab74b-13e6-4316-897d-bcf20047c7d4.png"></br>
   -  삭제는 postman을 보니 서버에 오류가 있는 것 같아 내일 말씀 드리고 다시 확인해보겠습니다!(삭제까지 확인하고 재코멘트 올리겠습니다.)</br>
   - 슬렉에 올렸던 질문은 이해하고 수정해줬습니다..! 감사합니다!
   -  밑에 실행화면 첨부해봅니다..!</br>

![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-16 at 02 13 08](https://user-images.githubusercontent.com/77050826/173886349-a3f5053a-899b-4c7c-a0d6-804cfc7ba338.gif)


### Question
<img width="588" alt="image" src="https://user-images.githubusercontent.com/77050826/173887240-99e497ca-2ee3-4cc9-83ac-92641cfb0c48.png"></br>
   - 이쪽 관련해서 여쭤보고 싶은게 있습니다!</br>
   - 혹시 현재 나온 api들로 이쪽이 로직 연결이 가능한가요? 아니면 제가 직접 해몽 관련 api를 이쪽에서 연결해줘야하는건지 좀 헷갈려서 여쭤봅니다..!</br>

2022-06-16 01:33 UTC, GREENOVER commented
@MoSonLee 
말씀하신 화면 이동 구현 같은 경우에는 api로 해줄 수 없습니다.
즉 화면 이동을 직접 구현해야되는것입니다.
여쭤보신 부분이 맞을까요?
또한 말씀하신것처럼 최종적으로 수정 및 구현이 다 완료되면 리뷰나 테스트를 진행할께요!

2022-06-16 10:51 UTC, MoSonLee commented
### Description
   - deleteDiary, getDiary연결했습니다.</br>
   - 이슈가 있었던 dictionary 관련된것 때문에 찾아보니 [Diary] 타입을 return 시켰는데 Diary위에 cardList를 만들어줘서 해결했습니다!</br>
      - Postman 확인해보니 cardList로 하나 감싸주고 있더라고요..!
         - <img width="300" alt="image" src="https://user-images.githubusercontent.com/77050826/174053886-36c2ef2b-139f-417c-9c64-a2728147d48e.png"></br>
         - 현재 다이어리 저장 후 보관함으로 가야하는데 record쪽이 완료되지 않아 postman으로 값을 넣어줘서 확인했습니다.</br>
   - 이전 코멘트에도 작성했었지만 서버에선 날짜가 String type으로 오고 있고 저희는 DatetoStr을 사용해서 다이어리가 보관함에 뜨지 않아 우선 이렇게 확인했습니다!
      - ![image](https://user-images.githubusercontent.com/77050826/174054228-00f730b1-0bbd-4141-81b5-5bd97b91f34a.png)</br>
   - 전체적인 바뀐 url 값들 다 변경해주었습니다.</br>
   - 피그마를 확인해보니 해몽 보러가기를 눌렀을 때는 검색하기 쪽으로 다시 가는걸로 확인해서 관련된 Mark 부분과 edit했을때 편집하기 이동쪽은 현재 기록, 검색하기가 되어있지 않아서 처리해주지 않았습니다.</br>

![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-16 at 19 37 55](https://user-images.githubusercontent.com/77050826/174053407-e3ca2ff1-cea4-454b-b426-dfaeed235e56.gif)

2022-06-17 01:42 UTC, GREENOVER commented
@MoSonLee 
고생 많으셨습니다!
우선 코멘트로 궁금한 부분 및 수정되어야할 부분들에 대해 남겼습니다.
또한 이슈 하나 제보합니다.
승후님 영상에서도 확인이 가능한데 꿈 일기를 삭제하고 보관함에 "이번달에는 X번의 꿈을 꾸었어요"에서 해당 count가 변하지 않습니다.
아마 setCount 메서드가 해당 보관함 onAppear시에만 불리고 해몽 삭제 되었을때 불리지 않아 동기화가 되지 않는것으로 보입니다.
해당 메서드 호출만 적절한 위치에 심어주면 될것 같아요.

2022-06-17 01:44 UTC, GREENOVER requested changes
코멘트 확인 및 수정 부탁드립니다🙋🏻

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +import SwiftUI
SwiftUI 프레임워크 임포트가 필요한가요?
Foundation이면 충분할것 같아요🙋🏻

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +  }
다른곳과 코드 통일성을 위해 이니셜라이저 전으로 해당 구현부를 옮기면 어떨까요?

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +public struct DiaryList: Decodable, Equatable, Hashable {
제가 모델 타입 설계 시 놓쳤던 부분이네요! 
바로잡아주셔서 감사합니다🙇🏻

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +public struct DiaryList: Decodable, Equatable, Hashable {
Equatable과 Hashable 프로토콜을 채택해주신 이유가 있으신가요?

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
> +    cardID: [String],
일기 수정은 하나씩 밖에 할 수 없는것으로 알고 있고
노션 API 명세에도 아래와 같이 Dto를 보면 어레이가 아닌것으로 보이는데 바꾸신 이유가 있나요?
![스크린샷 2022-06-17 오전 9 57 28](https://user-images.githubusercontent.com/72292617/174201450-dfd3be0f-1ef5-421e-b244-942942fbf8ba.png)

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
> +    cardID: [String],
이 부분도 위와 마찬가지의 코멘트지만 타입을 어레이로 해주신 이유가 궁금해요.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/EditDiaryRequestDto.swift
> +  public var cardID: [String]
어레이로 타입 변경된 이유가 궁금합니다🙋🏻

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Dream/DreamCore.swift
> +      // MARK: - 추후 꿈 카드 검색 후 저장 시 보관함 가기 로직 구현 (AppAction에서 필요) -> 완료
앱 코어에서 해당 구현 확인했습니다!
해당 주석은 이제 제거되어도 되겠네요👍

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +    isCardResultPushed: Bool = true
해당 프로퍼티는 어디서 쓰이는것이며 현재 사용되고 있나요?

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +  case setDeleteDiaryList
실제 어떤 역할을 해주나요 해당 액션이?🙋🏻

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            popToRoot()
꿈 일기 상세에서 삭제하게 되고 성공하면 popToRoot가 불리는데
최상단으로 뷰가 이동하는것인데 여기서 실제 최상단뷰는 어떤 화면인가요?

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .setDeleteDiaryList)
해당 setDeleteDiaryList 액션으로 리턴하는 이유가 어떤걸까요?

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
>  enum DiaryAction {
토스트 액션을 사용한다면 ToastPresentableAction 프로토콜 채택이 필요합니다.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .presentToast("꿈 일기가 삭제되지 않았어요. 다시 시도해주세요."))
해당 토스트 메시지가 정상적으로 노출되는지 테스트 해보셨나요?
안불릴거에요 아마.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      return .none
액션 정의는 backButtonTapped 액션 다음으로 되어있는데 실제 구현은 최하단에 있어 액션 순서를 유추하기 힘듭니다.
액션 정의한 흐름에 맞추면 좋을것 같아요.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      // MARK: - 꿈 일기 삭제 API 호출 필요 -> 완료
해당 구현부 확인했습니다!
주석은 제거되어도 될듯 합니다.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +          diaryListService: $0.diaryService )
)를 개행하거나 한 라인에 붙여쓰거나 컨벤션을 맞추면 좋을것 같습니다.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  // MARK: - 추후 유저가 저장한 꿈일기에 대해 받아오는 API 및 로직 필요 -> 완료
구현 확인했습니다! 주석은 제거되어도 될것 같습니다.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  let deleteDiaryID = state.local.deleteDiaryList
해당 상수의 타입이 어레이일테니 deleteDiaryIDs 혹은 deleteDiaryIDList의 네이밍은 어떨까요?
현재는 단수형의 느낌이 강합니다.

2022-06-17 01:44 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +//    WithViewStore(store.scope(state: \.local.diaryListWithDate)) { diaryListViewStore in
이부분은 단순 Diary 모델 타입에서 받아오는 registerDate를 그대로 사용하는것이 아닌 해당 String으로 넘어오는 날짜를 저희의 형식인 `convertDateToString` 등의 메서드를 사용하거나 필요하다면 해당 문자열을 원하는 문자열 즉 날짜형식이 (2022.07.01) 처럼 되어야 하는것으로 변환시켜 프로퍼티를 하나 만들어줘야될것 같아요.
그다음에 해당 프로퍼티를 사용하면 해당 기존 코드이 수정 없이 사용될 수 있습니다.
즉 StorageCore에서 기존 구현되 있던
```swift
public var diaryListWithDate: [Diary] {
    diaryList?.filter {
      $0.date.contains(self.selectedDateToStr)
    } ?? []
  }
```
여기서 $0.date를 $0.convertedDate로 바뀌면 해결되겠네요.
정리하자면 Diary 모델 타입에서 받아온 string date 프로퍼티를 가지고 저희가 원하는 날짜 형식인 2022.07.01과 같이 변경할 수 있도록 연산 프로퍼티 추가하고 그 프로퍼티를 사용하면 됩니다.

2022-06-17 04:51 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +import SwiftUI
앗 그렇네요 수정해주었습니다!

2022-06-17 04:52 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +  }
넵 수정해주었습니다!

2022-06-17 04:53 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/DiaryList.swift
> +public struct DiaryList: Decodable, Equatable, Hashable {
아 필요하지 않겠네요..! 삭제해주었습니다!

2022-06-17 04:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
> +    cardID: [String],
아 제가 생각을 잘못해 모든 cardId가 array타입으로 오는걸로 혼동했습니다! 
수정해주었습니다!

2022-06-17 04:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/DiaryService.swift
> +    cardID: [String],
수정해주었습니다!

2022-06-17 04:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/EditDiaryRequestDto.swift
> +  public var cardID: [String]
수정해주었습니다!

2022-06-17 04:56 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Dream/DreamCore.swift
> +      // MARK: - 추후 꿈 카드 검색 후 저장 시 보관함 가기 로직 구현 (AppAction에서 필요) -> 완료
넵! 삭제해주었습니다!

2022-06-17 04:57 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +    isCardResultPushed: Bool = true
아 테스트할때 사용해볼라고 만들고 지워줬었는데 남아있었네요..! 죄송합니다ㅜㅜ 삭제해주었습니다!

2022-06-17 05:03 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .setDeleteDiaryList)
아 그러네요..! deleteDiaryList로 변경해주었습니다!

2022-06-17 05:09 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            popToRoot()
mainTabCore의 storagr가 탭된 상태로 이동하는것이라 생각하고 사용해주었습니다.!

2022-06-17 05:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
>  enum DiaryAction {
추가해주었습니다!

2022-06-17 05:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .presentToast("꿈 일기가 삭제되지 않았어요. 다시 시도해주세요."))
위에 ToastPresentableAction를 추가해주지 않아서 생긴 문제 같습니다!

2022-06-17 05:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      return .none
넵 위치 옮겨주었습니다!

2022-06-17 05:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      // MARK: - 꿈 일기 삭제 API 호출 필요 -> 완료
넵 삭제해주었습니다!

2022-06-17 05:13 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +          diaryListService: $0.diaryService )
아 그렇겠네요..! 개행해주었습니다!

2022-06-17 05:14 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  // MARK: - 추후 유저가 저장한 꿈일기에 대해 받아오는 API 및 로직 필요 -> 완료
넵 삭제해주었습니다!

2022-06-17 05:15 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  let deleteDiaryID = state.local.deleteDiaryList
넵! deleteDiaryIDList로 네이밍 수정해주었습니다!

2022-06-17 05:31 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .presentToast("꿈 일기가 삭제되지 않았어요. 다시 시도해주세요."))
그거랑 별개의 문제일거에요.
현재 저희 앱은 AppCore에서 toast를 띄워주고 있는 형태인데 해당 토스트처리가 AppCore에서 풀백받아 사용되고 있지 않을거에요.
이를 추가해줘야합니다.

2022-06-17 08:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +//    WithViewStore(store.scope(state: \.local.diaryListWithDate)) { diaryListViewStore in
여기 관련해서 문제를 조금 겪고 있어서요..! ㅜㅜ
만들어주신 Date+extenstions에 String type을 데이트로 바꿔주는 것을 추가하고
<img width="461" alt="image" src="https://user-images.githubusercontent.com/77050826/174255867-05ecba29-73ee-4507-be32-64222262dc4a.png">
Diary에서 저희가 서버에서서 받아온 date(String 타입형을 제가 만들어준 func를 사용해 -> Date 
다시 Date -> String으로 해주고 있는데 화면에 뜨질 않아서요..! ㅜㅜ
<img width="561" alt="image" src="https://user-images.githubusercontent.com/77050826/174255946-2e95169f-fc7a-4baf-b3c4-b64c998f1c1b.png">

2022-06-17 08:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .presentToast("꿈 일기가 삭제되지 않았어요. 다시 시도해주세요."))
<img width="543" alt="image" src="https://user-images.githubusercontent.com/77050826/174256369-0fe627f6-84da-4c6c-80a4-42ef0d6fb208.png">
이렇게 추가해주었습니다!

2022-06-17 08:15 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +//    WithViewStore(store.scope(state: \.local.diaryListWithDate)) { diaryListViewStore in
목데이터를 넣어보셔서 실제 서버에서 주는 string 형식이 convertStringToDate를 통해 원하는 Date로 반환되는지 확인을 해보시고
하는 과정들을 디버깅해보면 좋을것 같습니다.
그거 외에 제 생각엔 굳이 string으로 들어온 값을 Date로 바꾸고 다시 string으로 변경하는 이유를 잘 모르겠습니다.
들어온 string을 저희가 원하는 string 타입으로 바꾸는게 더 적절하지 않을까해서요.

2022-06-17 08:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +            return Effect(value: .setDeleteDiaryList)
음 말씀으로 어떻게 변경된건지 잘 모르겠어서 추후 코드로 보겠습니다!

2022-06-17 08:22 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +  case setDeleteDiaryList
삭제해주었습니다!

2022-06-17 09:01 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +//    WithViewStore(store.scope(state: \.local.diaryListWithDate)) { diaryListViewStore in
<img width="313" alt="image" src="https://user-images.githubusercontent.com/77050826/174265272-5d18d9d8-a700-4c0f-8afe-47eb629a2e35.png">
이해했습니다! String -> String으로 바로 갈 생각을 못하고 String -> Date -> String으로 생각했어서 생겼던 문제 같습니다!  감사합니다!

2022-06-17 09:11 UTC, MoSonLee commented
### Description
   - 리뷰 정말 감사합니다 찬우님! :bow:! 올려주신 리뷰 토대로 하나씩 수정해 pr 올려봤습니다..!
   - 우선 setdiarycount 로직을 deleteDiary해줄때도 추가해줬습니다..!
      - 제 기기 문제인지 확실하진 않은데 이게 storageTab을 눌렀을 때 바로 다이어리 갯수가 갱신되진 않고 있습니다 ㅜㅜ
   - 그외에는 해주신 코멘트 토대로 모두 고쳐봤습니다!

2022-06-17 15:01 UTC, GREENOVER commented
기기 문제는 아니고 실제 해당 탭이 되었을때 다이어리 갯수를 설정해주는게 불리는지 확인해보셔야 될것 같습니다!
확실한건 기기와는 전혀 무관하며 로직의 결함 혹은 누락된 부분이 있을거에요..!
이 부분도 추가되면 재리뷰하겠습니다.

2022-06-17 15:54 UTC, MoSonLee commented
### Description
   - 확인해보니 onAppear될 때 setDiaryCount를 해주면 count를 해주기 전에 diary들이 set 돼서 0으로 뜨고 다이어를 누르고 뒤로 갔을 때 count를 바꿔주는 것 같습니다.</br>
   - onAppear에서 count해주지 않고 setDiaryList, deleteDiaryList 액션 부분에서 rerturn으로 setdiarycount를 해주니 문제 없이 깔끔하게 count가 되게 수정해주었습니다.!</br>
   - 실행 화면 첨부해봅니다.!</br>
      - ![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-18 at 00 47 29](https://user-images.githubusercontent.com/77050826/174333666-adabfd1d-7c83-435c-b4fe-167764992186.gif)

2022-06-17 15:54 UTC, MoSonLee commented
### Description
   - 확인해보니 onAppear될 때 setDiaryCount를 해주면 count를 해주기 전에 diary들이 set 돼서 0으로 뜨고 다이어를 누르고 뒤로 갔을 때 count를 바꿔주는 것 같습니다.</br>
   - onAppear에서 count해주지 않고 setDiaryList, deleteDiaryList 액션 부분에서 rerturn으로 setdiarycount를 해주니 문제 없이 깔끔하게 count가 되게 수정해주었습니다.!</br>
   - 실행 화면 첨부해봅니다.!</br>
      - ![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-18 at 00 47 29](https://user-images.githubusercontent.com/77050826/174333666-adabfd1d-7c83-435c-b4fe-167764992186.gif)

2022-06-17 15:54 UTC, MoSonLee commented
### Description
   - 확인해보니 onAppear될 때 setDiaryCount를 해주면 count를 해주기 전에 diary들이 set 돼서 0으로 뜨고 다이어를 누르고 뒤로 갔을 때 count를 바꿔주는 것 같습니다.</br>
   - onAppear에서 count해주지 않고 setDiaryList, deleteDiaryList 액션 부분에서 rerturn으로 setdiarycount를 해주니 문제 없이 깔끔하게 count가 되게 수정해주었습니다.!</br>
   - 실행 화면 첨부해봅니다.!</br>
      - ![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-18 at 00 47 29](https://user-images.githubusercontent.com/77050826/174333666-adabfd1d-7c83-435c-b4fe-167764992186.gif)

2022-06-18 01:30 UTC, GREENOVER requested changes
추가 리뷰 드렸습니다!

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> +// extension Diary {
해당 Stub 코드 주석을 친 이유가 있나요?

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/DeleteDiaryRequestDto.swift
> +    case idList = "idList"
키가 같은데 코딩키로 rawValue를 주신 이유가 있나요?

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      popToRoot()
실제 아래에서 일기 삭제에 대해 성공 시에만 빠져나와야하지 않을까요?
현재 로직이라면 얼럿에 버튼이 탭 되었을때 삭제 되기도 전에 먼저 빠져나오게 되는것 같아요.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +  case deleteDiaryList
해당 액션이 사실상 아무 기능을 안해주고 있는데 액션 네이밍만 보면
일기 리스트를 삭제해주는것으로 혼동이 옵니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  // MARK: - 추후 꿈일기 삭제 API 및 로직 필요 -> 완료
주석 없어도 될것 같아요.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +
개행할 필요가 없어보입니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +public func convertDateFormatter(date: String) -> String {
위의 컨벤션과 동일하게 언더스코어를 사용하면 어떨까요?
굳이 date 파라미터 라벨을 붙여줄 이유가 크게 없을것 같아요.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  dateFormatter.timeZone = NSTimeZone(name: "KST") as TimeZone?
타임존 설정이 필요한가요?🙋🏻

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  dateFormatter.timeZone = NSTimeZone(name: "KST") as TimeZone?
타임존 설정이 필요한가요?🙋🏻

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  return timeStamp
return 라인 전 개행이 있으면 더 가독이 좋을것 같습니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  let convertedDate = dateFormatter.date(from: date)
convertedDate 라인 전 개행이 있으면 가독이 더 좋을것 같습니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  return timeStamp
현재 반환되는 값에 timeStamp라는 네이밍이 조금 어색해보여요.
우리가 필요한건 "yyyy.mm.dd"의 반환인데 타임스탬프는 아예 다른 시간 형태를 나타냅니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
>    public let date: String
해당 date는 외부에서 이제 쓰이나요?
convertedDate로 사용이 다 대체될 수 있는지 아니면 필요하다면 어디서 필요한가요?

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      return .none
실제 의미없는 액션은 아니지만 네이밍가 구현이 맞지 않습니다.

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +      return setDiaryCount(state: &state)
아래 `case .deleteCardAlertModal(.primaryButtonTapped):`의 액션에서도 setDiaryCount가 발행되고
여기서도 발행되어 중첩되는걸로 보이는데 이유가 있나요?

2022-06-18 01:30 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +            Text(convertedDate)
굳이 기존 date 네이밍을 변환시킨 이유가 있을까요?
DiaryCardView만 보면 현재 들어오는 date가 변환된 Date라고 네이밍이 명시되어 사용될 이유가 있을까해서요..!
즉 현재 뷰에서는 얘가 변환된 날짜인지로의 관심사는 필요없을것 같아요.

2022-06-18 03:10 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> +// extension Diary {
앗 수정해주었습니다!

2022-06-18 03:11 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/RequestDto/DiaryDto/DeleteDiaryRequestDto.swift
> +    case idList = "idList"
앗 그러네요 수정해주었습니다!

2022-06-18 03:15 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      popToRoot()
넵! 수정해주었습니다!

2022-06-18 03:16 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +  // MARK: - 추후 꿈일기 삭제 API 및 로직 필요 -> 완료
넵!

2022-06-18 03:17 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +public func convertDateFormatter(date: String) -> String {
넵 수정해주었습니다!

2022-06-18 03:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  return timeStamp
넵! 수정해주었습니다!

2022-06-18 03:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  dateFormatter.timeZone = NSTimeZone(name: "KST") as TimeZone?
아 필수적 요소가 아니었군요! 삭제해주었습니다!

2022-06-18 03:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  dateFormatter.timeZone = NSTimeZone(name: "KST") as TimeZone?
삭제해주었습니다!

2022-06-18 03:20 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  let convertedDate = dateFormatter.date(from: date)
네 추가해주었습니다!

2022-06-18 03:20 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  return timeStamp
time으로 수정해주었습니다!

2022-06-18 03:23 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
>    public let date: String
private으로 선언 후 외부에서 date -> convertedDate로 바꾸어주었습니다!

2022-06-18 03:28 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +      return setDiaryCount(state: &state)
길게 눌러서 삭제 할 때와 안에서 삭제 할때 모두 counT 해줘야 한다고 생각해서요..!
실제로도 저 문구를 삭제 시 길게 탭했을 때 count가 되지 않는 모습을 보여줘서요..!
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-06-18 at 12 27 40](https://user-images.githubusercontent.com/77050826/174421143-53048230-80c2-49b9-b382-fd90d51315b5.gif)

2022-06-18 03:30 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageView.swift
> +            Text(convertedDate)
네 이해했습니다 수정해주었습니다!

2022-06-18 03:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +  case deleteDiaryList
넵 삭제해주었습니다!

2022-06-18 03:34 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +
넵 수정해주었습니다!

2022-06-18 03:48 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Extensions/Date+extensions.swift
> +  return timeStamp
음 time보다는 큰 의미에서 date를 담는 무언가의 네이밍이 필요해보여요.
time만의 네이밍은 몇시몇분몇초 즉 시간을 의미하지 않을까해요.

2022-06-18 03:50 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +      return setDiaryCount(state: &state)
아하 이해했습니다.
혹시 첨부로 보여준 캡쳐 영상은 저 코드를 제거하고 잘못된 케이스를 보여주신게 맞을까요?

2022-06-18 03:54 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/StorageCore.swift
> +      return setDiaryCount(state: &state)
넵 저 코드를 제거 후 찍은 영상입니다!

2022-06-18 03:55 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Feature/Storage/Diary/DiaryCore.swift
> +      return .none
넵 삭제해주었습니다!

2022-06-18 04:01 UTC, MoSonLee commented
### Description
   - 코드 리뷰들을 토대로 전반적 코드 전부 수정해줬습니다! 감사합니다..!

2022-06-18 04:10 UTC, GREENOVER requested changes
고생하셨습니다!
인덴트 컨벤션이 맞지 않는 부분 하나만 수정부탁드립니다!

2022-06-18 04:10 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> + }
인덴트 맞춰주세요..!

2022-06-18 04:12 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> + }
넵 수정해주었습니다!

2022-06-18 04:17 UTC, GREENOVER requested changes
하나 더 있습니다🥲

2022-06-18 04:17 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> + extension Diary {
여기부터 인덴트가 잘못되있습니다~!

2022-06-18 04:19 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Models/Diary.swift
> + extension Diary {
수정해주었습니다..! 죄송합니다 기본적인걸 ㅜㅜ😭😭

2022-06-18 04:37 UTC, GREENOVER approved these changes
수고 많으셨습니다!
머지 부탁드립니다!

2022-06-18 04:48 UTC, MoSonLee commented
### Description
   - 최신 상태 Merge 시켜줬습니다!

2022-06-18 04:56 UTC, GREENOVER approved these changes
수고하셨습니다. 머지하겠습니다!

2022-06-18 04:56 UTC, merged