fix: add deleteToken in dropout service
depromeet/mongsil-iOS pull request #83
Opened 2022-06-26 15:26 UTC by MoSonLee

### Task
   - 회원 탈퇴시 토큰삭제 로직 추가하기

2022-06-27 00:38 UTC, GREENOVER requested changes
unlink를 잘 파악하시고 적용해주셨어요!
기능의 문제는 없지만 코드 관심사가 조금 다르고 로직의 결함이 하나 존재해 수정해주시면 감사하겠습니다!
또 만약 카카오로 이메일 동의없이 소셜 로그인 시 이를 캐치해 "이메일 동의를 해주셔야 정상적인 기능 사용이 가능합니다. 탈퇴 후 재 로그인 해주세요."와 같은 토스트 메시지를 띄워주는것까지 보완되면 이 Task는 마무리 지을 수 있을것 같습니다!
(애플의 경우는 필요없습니다..!)
++ 추가로, 생각난건데 지인분들이 정상적으로 이메일 동의하고 가입했는데도 기능이 안되었던건 아마도 어제 서버 수정 및 배포시간에 맞물리거나 했을 가능성도 있을것 같아요.
(한번 지인분들이 대부분 비슷한 시간대에 진행하셨는지 물어보시면 확실히 알 수 있을것 같습니다!)

2022-06-27 00:38 UTC, GREENOVER commented on Mongsil/Mongsil/Module/Component/Services/DropoutService.swift
> +          }
얘네 로직은 DropoutService에서가 아닌 KakaoLoginService에서 구성해주는게 더 적절해보입니다🙋🏻
또한 지금같은 경우 애플 계정으로 탈퇴시에도 해당 로직을 타게 되는데 그럴 필요가 있을까해요.
카카오 계정으로 탈퇴 시에만 해당 로직을 타게 해주면 어떨까요?
즉 정리하자면 카카오 계정일때만 해당 로직을 태워주도록하는것 + 로직이 KakaoLoginService에 존재해야하는것을 합쳐 이것을 dropout을 호출하는 코어에서 진행해줘야할것 같습니다.

2022-06-27 16:08 UTC, MoSonLee commented on Mongsil/Mongsil/Module/Component/Services/DropoutService.swift
> +          }
수정해주었습니다!

2022-06-27 16:21 UTC, MoSonLee commented
### Task
   - unlink logic 위치를 dropoutservice에서 kakaologinservice가 사용되는쪽으로 수정해주었습니다!
   - email 정보 제공 동의가 없으면 toast 메시지를 띄워주고 유저가 다시 
   maintab -> setting -> profile -> dropout -> 재가입을 하는 플로우 자체가 너무 많은 플로우를 거쳐야하고 이렇게 되면 유저가 이용하지 않을 것 같다고 생각했습니다.!
      - **solution**: 유저가 이메일 정보 제공 동의를 해주지 않으면 바로 토큰 삭제 + toast message에 "이메일 동의를 해주셔야 정상적으로 기능 사용이 가능합니다! 이메일 정보 제공에 동의해주세요!"를 띄워줬습니다.! 
      - 이렇게 하면 유저가 다시 카카오 로그인 버튼을 누르고 정보 제공 동의를 누르면 훨씬 빠르게 할 수 있을것 같다고 생각했습니다.!
      - 일단 뭐든 임시 방안이라 생각해서 사용자가 최대한 이용하기 쉬운 방안으로 생각해봤습니다..!(규정상 문제가 있으면 바로 수정하겠습니다.!)
      - 실행화면 첨부해보겠습니다!</br>
      - ![Simulator Screen Recording - iPhone 13 - 2022-06-28 at 01 07 10](https://user-images.githubusercontent.com/77050826/175988317-e7c00b6c-e786-464c-ace6-df792bd63d04.gif)</br>


### Question
   - 혹시 위처럼 카카오 이메일 정보 제공 동의를 해주지 않으면 회원가입 자체를 막아버리게 되면 애플 혹은 카카오 규정에 어긋나는 것이 있는지 정확히 확인이 안되어서요..! 너무 강제화하는게 문제가 된다면 비효율적이지만 유저가 회원탈퇴를 하는 로직으로 수정해보겠습니다..!

2022-06-27 23:09 UTC, GREENOVER requested changes
승후님이 대안으로 해주신 방법이 더 베스트이고 너무 좋습니다!👍👍👍
기능상으로는 그렇게함이 완벽하다고 보여요ㅎㅎ
정책상 문제는 안될거 같은데 심사는 올려봐야 정확히 알 수 있을것 같습니다. 저도 자세하게는 모르겠어요ㅠ
우선 그렇게 가시죠!
다만 UserApi.shared.unlink 하는 로직이 어떻게보면 다 서비스의 로직인데 현재 코어단에서 직접적으로 사용하고 있어 TCA의 기조와 어긋나다고 보입니다.
리듀서는 순수해야합니다!
해당 사이드이펙트들은 KakaoLoginService에서 로직을 구현하고 이를 env에서 호출하여 사용하는게 맞을것 같아요..!
전부 사이드이펙트 처리들은 그렇게 되어 있어서 참고하시면 도움이될것 같습니다.
혹시 너무 오래걸리거나 한다면 해당 PR을 우선적으로 이번주 배포 후 바로 이어서 Task를 진행해보셔도 좋을것 같습니다.
한번 해보시고 일정 내 가능한지 여부 말씀해주세요!

2022-06-28 09:25 UTC, MoSonLee commented
### Description
   - 우선 이메일 수신 정보 동의를 한 상태에서도 회원가입이 제대로 되지 않는 경우 영상을 받아서 확인해보니
      - 로그인을 완료했어요! -> 회원가입에 실패했습니다 -> 이순으로 toast message가 뜨는걸 확인했습니다.
      - 그래서 생각한게 setLogininfo 로직과 signupUser 쪽 로직의 순서가 문제가 되는거 아닐까 라는 생각을 했습니다..!
      - <img width="391" alt="image" src="https://user-images.githubusercontent.com/77050826/176143611-0054951a-0ed8-44d9-b277-0d122a2f71c4.png">
      - <img width="376" alt="image" src="https://user-images.githubusercontent.com/77050826/176143684-6210b291-3f2c-422e-96e1-e058f6ce56d4.png">
      - 저희 원래 코드를 확인해보면 delay가 걸려 있던거 같은데 그 사이에 회원가입 로직을 처리하지 못해서 생기는 문제 아닐까라고 추측했습니다.!
      - 그래서 delay 수치들을 좀 다르게 하고 넣어줘봤습니다..!
   - 근데 제 디바이스와 실기기에는 문제가 없는 상태라 추측으로 로직들을 생각해줘야해서 확실하진 않을것 같습니다..!
   - 아마 무슨 방법이든 재배포가 된 후에 확인을 해봐야 확실히 알것 같은데 우선 이런 방향으로 생각해봤습니다..!

2022-06-29 00:39 UTC, GREENOVER approved these changes
음 네 좋습니다 승후님!
우선 이슈 리포트가 힘드니 이렇게 딜레이 시간을 늘려줘서 확인을 해봐야겠네요..!
그런데, signUp 딜레이를 0.05초 거는걸로는 크게 유의미한 시간이 아니라 또 발생할 여지가 있어 그때마다 시간텀을 수정해서 상용 배포 빌드에서 확인하는것보다 0.3초 정도로 걸어서 확실히 여기의 로직 문제인지 판단하는게 나아보입니다!
300으로 늘리는건 제가 바로 그냥 푸쉬하고 해당 PR 머지 후 배포 진행하겠습니다.
이어서 새로운 브랜치에서 토큰 삭제에 대해 서비스 레이어로 코드 이관등의 리팩토링 작업해주시면 감사하겠습니다!

2022-06-29 00:42 UTC, merged